<p class="ect-padding-lr ect-margin-tb ect-margin-bottom0"><?php echo $this->translate('您可通过 电子邮件 重置密码'); ?>
    <a href="<?php echo $this->url('m_user/default',array('action'=>'phoneforgotpasswd')); ?>" class="btn btn-primary ect-colorf"><?php echo $this->translate('点击通过手机号码重置'); ?></a>
</p>
<form class="validforms" method="post">
    <div class="flow-consignee ect-bg-colorf">
        <section>
            <ul>
                <li>
                    <div class="input-text"><b><?php echo $this->translate('会员名称'); ?>：</b><span><input type="text" datatype="*" id="user_name" class="inputBg" name="user_name" placeholder="<?php echo $this->translate('会员名称'); ?>" nullmsg="<?php echo $this->translate('请填写会员名称信息'); ?>"></span></div>
                </li>
                <li>
                    <div class="input-text"><b><?php echo $this->translate('会员邮箱'); ?>：</b><span><input type="text" datatype="e" class="inputBg" name="user_email" placeholder="<?php echo $this->translate('会员邮箱'); ?>" nullmsg="<?php echo $this->translate('请填写会员邮箱信息'); ?>"></span></div>
                </li>
            </ul>
        </section>
    </div>



    <div class="ect-padding-lr ect-padding-tb"> <input type="submit" value="提交" class="btn btn-info ect-btn-info ect-colorf"></div>
</form>