    		<div id="sticky_navigation" style="height:30px;border-bottom:4px solid #DFDFDF;">
        	<p class="pull-left" style="font-size:16px; line-height:30px;"><strong><?php echo $this->translate('数据库备份'); ?> </strong><SMALL style="color:#F00;"><?php echo $this->translate('当您的数据库非常之大时，建议同时使用专业备份工具进行备份'); ?></SMALL></p>
        	<p class="pull-right">
            <a href="<?php echo $this->url('dbsql/default/backup',array('action'=>'backup', 'sql_file_name'=>'dbshop' . substr(md5(time()),0,16), 'vol'=>'1', 'type'=>'stand')); ?>" class="btn btn-small btn-primary"><i class="icon-briefcase icon-white"></i> <?php echo $this->translate('备份当前系统数据'); ?></a>&nbsp;
            <a href="<?php echo $this->myviewalias()->dbshopHelpUrl('db_back'); ?>" target="_blank" class="btn btn-small btn-info"><i class="icon-info-sign icon-white"></i> <?php echo $this->translate('查看帮助说明'); ?></a>
            </p>
        	</div>
            <table class="table table-hover">
            <thead style="background:#CCC;">
            	<tr>
                    <th width="20%"><?php echo $this->translate('备份文件名'); ?></th>
                    <th width="12%"><?php echo $this->translate('备份时间'); ?></th>
                    <th width="10%"><?php echo $this->translate('备份大小'); ?></th>
                    <th width="10%"><?php echo $this->translate('备份卷标'); ?></th>
                    <th width="8%"><?php echo $this->translate('操作'); ?></th>
                </tr>
            </thead>
            <?php if($this->sql) foreach ($this->sql as $value) { 
				$name_substr = substr($value['name'],0,22);
			?>            
            <tr <?php if ($value['vol'] !=1) { ?>class="<?php echo $name_substr; ?>" style="display:none"<?php } ?>>
            	<td><?php if ($value['vol'] ==1) { ?><i class="icon-plus" onclick="rowClicked('<?php echo $name_substr; ?>');" id="<?php echo $name_substr; ?>" ></i> <?php } else { ?>&nbsp;&nbsp;&nbsp;&nbsp;<?php } echo $value['name']; ?></td>
                <td><?php echo $value['add_time']; ?></td>
                <td><?php echo $value['file_size']; ?></td>
                <td><?php echo $value['vol']; ?></td>
            	<td>
				<?php if ($value['vol'] ==1) { ?>
                <a onclick="return window.confirm('<?php echo $this->translate('您确实要执行该导入吗？'); ?>');" href="<?php echo $this->url('dbsql/default/backup',array('action'=>'importbackup', 'sql_file_name'=>$value['name'])); ?>"><?php echo $this->translate('导入'); ?></a><span>|</span><a href="javascript:;" onclick="return sql_del_js('<?php echo $value['name']; ?>');"><?php echo $this->translate('删除'); ?></a>
                <?php } ?>
                </td>  
            </tr>
            <?php
				}
			?>
            </table>
            
<script>
function rowClicked (str) {
	if($('.'+str).length>0) {
		if($('#'+str).attr('class') == 'icon-plus') {
			$('#'+str).attr('class','icon-minus');
			$('.'+str).show();
		} else {
			$('#'+str).attr('class','icon-plus');
			$('.'+str).hide();
		}
	}
}
//备份删除
function sql_del_js(sql_file_name) {
	if(window.confirm('<?php echo $this->translate('您确实要删除该备份吗？'); ?>')) {
	$.post("<?php echo $this->url('dbsql/default',array('action'=>'delbackup')); ?>",{sql_file_name:sql_file_name},
	function(data){
		if(data != 'false') {
			window.location.href='<?php echo $this->url('dbsql/default'); ?>';
			return true;
		} else {
			alert('<?php echo $this->translate('备份删除失败！'); ?>');
		}
	});
	}
	return false;
}
</script>