<div class="tabbable tabs-left">
    <ul class="nav nav-tabs">
        <li><h5><?php echo $this->translate('短信提醒设置'); ?></h5></li>
        <li class="active"><a data-toggle="tab" href="#system_a"><?php echo $this->translate('基本信息'); ?></a></li>
    </ul>
    <form class="form-horizontal" name="phone_message_form" id="phone_message_form" method="post">
        <div class="tab-content">
            <div id="sticky_navigation" style="height:30px;border-bottom:4px solid #DFDFDF;">
                <div class="pull-left" style="font-size:16px;line-height:30px;"><strong><?php echo $this->translate('短信提醒设置'); ?></strong></div>
                <div class="pull-right">
                    <a href="<?php echo $this->serverUrl(true); ?>" class="btn btn-small btn-warning"><i class="icon-repeat icon-white"></i> <?php echo $this->translate('刷新'); ?></a>
                    &nbsp;<button type="submit" class="btn btn-small btn-primary"><i class="icon-ok icon-white"></i> <?php echo $this->translate('保存提醒设置'); ?></button>
                    &nbsp;<a href="<?php echo $this->myviewalias()->dbshopHelpUrl('phone_message_set'); ?>" target="_blank" class="btn btn-small btn-info"><i class="icon-info-sign icon-white"></i> <?php echo $this->translate('查看帮助说明'); ?></a>
                </div>
            </div>
            <div id="system_a" class="tab-pane active">
                <div class="well admin_add_header_well"><?php echo $this->translate('手机短信'); ?></div>
                <div class="well admin_add_well">
                    <div class="message_one">
                    </div>
                    <div class="control-group">
                        <label for="input01" class="control-label"><?php echo $this->translate('设置类型'); ?>：</label>
                        <div class="controls">
                            <select name="phone_sms_type" id="phone_sms_type" onchange="select_phone_sms_type();" class="span2">
                                <option value="" <?php if(!isset($this->phonesms_config['shop_phone_sms']['phone_sms_type']) or empty($this->phonesms_config['shop_phone_sms']['phone_sms_type'])) echo 'selected="selected"'; ?>><?php echo $this->translate('无类型'); ?></option>
                                <option value="alidayu" <?php if(isset($this->phonesms_config['shop_phone_sms']['phone_sms_type']) and $this->phonesms_config['shop_phone_sms']['phone_sms_type'] == 'alidayu') echo 'selected="selected"'; ?>><?php echo $this->translate('阿里大于短信'); ?></option>
                                <option value="aliyun" <?php if(isset($this->phonesms_config['shop_phone_sms']['phone_sms_type']) and $this->phonesms_config['shop_phone_sms']['phone_sms_type'] == 'aliyun') echo 'selected="selected"'; ?>><?php echo $this->translate('阿里云短信(消息服务)'); ?></option>
                                <option value="newaliyun" <?php if(isset($this->phonesms_config['shop_phone_sms']['phone_sms_type']) and $this->phonesms_config['shop_phone_sms']['phone_sms_type'] == 'newaliyun') echo 'selected="selected"'; ?>><?php echo $this->translate('阿里云短信(云通信)'); ?></option>
                                <option value="qqCloud" <?php if(isset($this->phonesms_config['shop_phone_sms']['phone_sms_type']) and $this->phonesms_config['shop_phone_sms']['phone_sms_type'] == 'qqCloud') echo 'selected="selected"'; ?>><?php echo $this->translate('腾讯云短信'); ?></option>
                            </select>
                            &nbsp;&nbsp;<a href="http://www.alidayu.com/" target="_blank" class="alidayu-msset" style="display: none;">查看阿里大于官方网站</a>
                            &nbsp;&nbsp;<a href="https://cloud.tencent.com/" target="_blank" class="qq-cloud" style="display: none;">腾讯云官网</a>
                            <span class="alidayu-msset" style="display: none;"><?php echo $this->translate('新注册的阿里大于用户，请使用阿里云短信服务，阿里大于已经不支持新用户短信服务(大于已经被挪入阿里云)；对于老用户不受影响。'); ?></span>

                            <a href="http://www.aliyun.com/" target="_blank" class="aliyun-msset-info" style="display: none;">查看阿里云官方网站</a>
                        </div>
                    </div>
                    <div class="control-group alidayu-msset" style="display: none;">
                        <label for="input01" class="control-label"><?php echo $this->translate('签名名称'); ?>：</label>
                        <div class="controls">
                            <input type="text" name="alidayu_sign_name" id="alidayu_sign_name" value="<?php if(isset($this->phonesms_config['shop_phone_sms']['alidayu_sign_name'])) echo $this->escapeHtml($this->phonesms_config['shop_phone_sms']['alidayu_sign_name']); ?>" class="span3">
                        </div>
                    </div>
                    <div class="control-group alidayu-msset" style="display: none;">
                        <label for="input01" class="control-label">App Key(<?php echo $this->translate('应用'); ?>)：</label>
                        <div class="controls">
                            <input type="text" name="alidayu_app_key" id="alidayu_app_key" value="<?php if(isset($this->phonesms_config['shop_phone_sms']['alidayu_app_key'])) echo $this->escapeHtml($this->phonesms_config['shop_phone_sms']['alidayu_app_key']); ?>" class="span3">
                        </div>
                    </div>
                    <div class="control-group alidayu-msset" style="display: none;">
                        <label for="input01" class="control-label">App Secret(<?php echo $this->translate('应用'); ?>)：</label>
                        <div class="controls">
                            <input type="text" name="alidayu_app_secret" id="alidayu_app_secret" value="<?php if(isset($this->phonesms_config['shop_phone_sms']['alidayu_app_secret'])) echo $this->escapeHtml($this->phonesms_config['shop_phone_sms']['alidayu_app_secret']); ?>" class="span3">
                        </div>
                    </div>

                    <div class="control-group aliyun-msset" style="display: none;">
                        <label for="input01" class="control-label"><?php echo $this->translate('主题名称'); ?>：</label>
                        <div class="controls">
                            <input type="text" name="aliyun_app_topic" id="aliyun_app_topic" value="<?php if(isset($this->phonesms_config['shop_phone_sms']['aliyun_app_topic'])) echo $this->escapeHtml($this->phonesms_config['shop_phone_sms']['aliyun_app_topic']); ?>" class="span3">
                        </div>
                    </div>
                    <div class="control-group aliyun-msset" style="display: none;">
                        <label for="input01" class="control-label"><?php echo $this->translate('签名名称'); ?>：</label>
                        <div class="controls">
                            <input type="text" name="aliyun_sign_name" id="aliyun_sign_name" value="<?php if(isset($this->phonesms_config['shop_phone_sms']['aliyun_sign_name'])) echo $this->escapeHtml($this->phonesms_config['shop_phone_sms']['aliyun_sign_name']); ?>" class="span3">
                        </div>
                    </div>
                    <div class="control-group aliyun-msset" style="display: none;">
                        <label for="input01" class="control-label"><?php echo $this->translate('阿里云'); ?>AccessId：</label>
                        <div class="controls">
                            <input type="text" name="aliyun_app_key" id="aliyun_app_key" value="<?php if(isset($this->phonesms_config['shop_phone_sms']['aliyun_app_key'])) echo $this->escapeHtml($this->phonesms_config['shop_phone_sms']['aliyun_app_key']); ?>" class="span3">
                        </div>
                    </div>
                    <div class="control-group aliyun-msset" style="display: none;">
                        <label for="input01" class="control-label"><?php echo $this->translate('阿里云'); ?>AccessKey：</label>
                        <div class="controls">
                            <input type="text" name="aliyun_app_secret" id="aliyun_app_secret" value="<?php if(isset($this->phonesms_config['shop_phone_sms']['aliyun_app_secret'])) echo $this->escapeHtml($this->phonesms_config['shop_phone_sms']['aliyun_app_secret']); ?>" class="span3">
                        </div>
                    </div>
                    <div class="control-group aliyun-msset" style="display: none;">
                        <label for="input01" class="control-label"><?php echo $this->translate('接入地址'); ?>Endpoint：</label>
                        <div class="controls">
                            <input type="text" name="aliyun_app_endpoint" id="aliyun_app_endpoint" value="<?php if(isset($this->phonesms_config['shop_phone_sms']['aliyun_app_endpoint'])) echo $this->escapeHtml($this->phonesms_config['shop_phone_sms']['aliyun_app_endpoint']); ?>" class="span5">
                            <?php echo $this->translate('http(s)意思是 http 或者 https ，不要直接填写 http(s)。如果您的站点是 http 则使用 http ，如果您的站点是 https 那么使用https即可。'); ?>
                        </div>
                    </div>
                    <div class="control-group new-aliyun-msset" style="display: none;">
                        <label for="input01" class="control-label"><?php echo $this->translate('签名名称'); ?>：</label>
                        <div class="controls">
                            <input type="text" name="new_aliyun_sign_name" id="new_aliyun_sign_name" value="<?php if(isset($this->phonesms_config['shop_phone_sms']['new_aliyun_sign_name'])) echo $this->escapeHtml($this->phonesms_config['shop_phone_sms']['new_aliyun_sign_name']); ?>" class="span3">
                        </div>
                    </div>
                    <div class="control-group new-aliyun-msset" style="display: none;">
                        <label for="input01" class="control-label"><?php echo $this->translate('阿里云'); ?>AccessId：</label>
                        <div class="controls">
                            <input type="text" name="new_aliyun_app_key" id="new_aliyun_app_key" value="<?php if(isset($this->phonesms_config['shop_phone_sms']['new_aliyun_app_key'])) echo $this->escapeHtml($this->phonesms_config['shop_phone_sms']['new_aliyun_app_key']); ?>" class="span3">
                        </div>
                    </div>
                    <div class="control-group new-aliyun-msset" style="display: none;">
                        <label for="input01" class="control-label"><?php echo $this->translate('阿里云'); ?>AccessKey：</label>
                        <div class="controls">
                            <input type="text" name="new_aliyun_app_secret" id="new_aliyun_app_secret" value="<?php if(isset($this->phonesms_config['shop_phone_sms']['new_aliyun_app_secret'])) echo $this->escapeHtml($this->phonesms_config['shop_phone_sms']['new_aliyun_app_secret']); ?>" class="span3">
                        </div>
                    </div>

                    <div class="control-group qq-cloud" style="display: none;">
                        <label for="input01" class="control-label"><?php echo $this->translate('签名名称'); ?>：</label>
                        <div class="controls">
                            <input type="text" name="qqcloud_sign_name" id="qqcloud_sign_name" value="<?php if(isset($this->phonesms_config['shop_phone_sms']['qqcloud_sign_name'])) echo $this->escapeHtml($this->phonesms_config['shop_phone_sms']['qqcloud_sign_name']); ?>" class="span3">
                        </div>
                    </div>
                    <div class="control-group qq-cloud" style="display: none;">
                        <label for="input01" class="control-label"><?php echo $this->translate('腾讯云'); ?>AppID：</label>
                        <div class="controls">
                            <input type="text" name="qqcloud_app_key" id="qqcloud_app_key" value="<?php if(isset($this->phonesms_config['shop_phone_sms']['qqcloud_app_key'])) echo $this->escapeHtml($this->phonesms_config['shop_phone_sms']['qqcloud_app_key']); ?>" class="span3">
                        </div>
                    </div>
                    <div class="control-group qq-cloud" style="display: none;">
                        <label for="input01" class="control-label"><?php echo $this->translate('腾讯云'); ?>AppKey：</label>
                        <div class="controls">
                            <input type="text" name="qqcloud_app_secret" id="qqcloud_app_secret" value="<?php if(isset($this->phonesms_config['shop_phone_sms']['qqcloud_app_secret'])) echo $this->escapeHtml($this->phonesms_config['shop_phone_sms']['qqcloud_app_secret']); ?>" class="span3">
                        </div>
                    </div>

                    <hr>
                    <div class="control-group dbshop-sms" style="display: none;">
                        <label for="input01" class="control-label"><?php echo $this->translate('管理员手机号'); ?>：</label>
                        <div class="controls">
                            <input type="text" name="admin_phone" id="admin_phone" value="<?php if(isset($this->phonesms_config['shop_phone_sms']['admin_phone'])) echo $this->escapeHtml($this->phonesms_config['shop_phone_sms']['admin_phone']); ?>" class="span3">
                            <font color="red"><?php echo $this->translate('目前仅支持中国内地手机号码。'); ?></font>
                        </div>
                    </div>
                    <div class="control-group dbshop-sms" style="display: none;">
                        <label for="input01" class="control-label"><?php echo $this->translate('接收短信'); ?>：</label>
                        <div class="controls">
                            <label class="checkbox inline"><input <?php if(isset($this->phonesms_config['shop_phone_sms']['admin_submit_order_phone_message']) and $this->phonesms_config['shop_phone_sms']['admin_submit_order_phone_message'] == 1) echo 'checked'; ?> type="checkbox" name="admin_submit_order_phone_message" value="1"><?php echo $this->translate('订单提交'); ?></label>
                            <label class="checkbox inline"><input <?php if(isset($this->phonesms_config['shop_phone_sms']['admin_payment_order_phone_message']) and $this->phonesms_config['shop_phone_sms']['admin_payment_order_phone_message'] == 1) echo 'checked'; ?> type="checkbox" name="admin_payment_order_phone_message" value="1"><?php echo $this->translate('付款完成'); ?></label>
                            <label class="checkbox inline"><input <?php if(isset($this->phonesms_config['shop_phone_sms']['admin_ship_order_phone_message']) and $this->phonesms_config['shop_phone_sms']['admin_ship_order_phone_message'] == 1) echo 'checked'; ?> type="checkbox" name="admin_ship_order_phone_message" value="1"><?php echo $this->translate('发货完成'); ?></label>
                            <label class="checkbox inline"><input <?php if(isset($this->phonesms_config['shop_phone_sms']['admin_finish_order_phone_message']) and $this->phonesms_config['shop_phone_sms']['admin_finish_order_phone_message'] == 1) echo 'checked'; ?> type="checkbox" name="admin_finish_order_phone_message" value="1"><?php echo $this->translate('确认收货'); ?></label>
                            <label class="checkbox inline"><input <?php if(isset($this->phonesms_config['shop_phone_sms']['admin_cancel_order_phone_message']) and $this->phonesms_config['shop_phone_sms']['admin_cancel_order_phone_message'] == 1) echo 'checked'; ?> type="checkbox" name="admin_cancel_order_phone_message" value="1"><?php echo $this->translate('取消订单'); ?></label>
                        </div>
                    </div>
                    <hr>
                    <div class="alidayu" style="display: none;">
                        <font color="red"><?php echo $this->translate('模板ID是空，为关闭此信息提醒；如果模板ID非空，为开启此信息提醒。'); ?></font><br>
                        <b>目前官方提供的可设置标签有 ${buyname} 购买人、${ordersn} 订单编号、${ordertotal} 订单金额、${expressname} 快递名称、${expressnumber} 快递单号</b>
                    </div>
                    <div class="qq-cloud" style="display: none;">
                        <font color="red"><?php echo $this->translate('模板ID是空，为关闭此信息提醒；如果模板ID非空，为开启此信息提醒。'); ?></font><br>
                        <b>目前官方提供的可设置标签有 {1} 购买人、{2} 订单金额、{3} 订单编号、{4} 快递名称、{5} 快递单号</b>
                    </div>
                    <br>
                    <div class="control-group dbshop-sms" style="display: none;">
                        <label for="input01" class="control-label"><?php echo $this->translate('订单提交模板ID'); ?>：</label>
                        <div class="controls">
                            <input type="text" name="alidayu_submit_order_template_id" id="alidayu_submit_order_template_id" value="<?php if(isset($this->phonesms_config['shop_phone_sms']['alidayu_submit_order_template_id'])) echo $this->escapeHtml($this->phonesms_config['shop_phone_sms']['alidayu_submit_order_template_id']); ?>" class="span3">
                        </div>
                    </div>
                    <div class="control-group dbshop-sms" style="display: none;">
                        <label for="input01" class="control-label"><?php echo $this->translate('付款完成模板ID'); ?>：</label>
                        <div class="controls">
                            <input type="text" name="alidayu_payment_order_template_id" id="alidayu_payment_order_template_id" value="<?php if(isset($this->phonesms_config['shop_phone_sms']['alidayu_payment_order_template_id'])) echo $this->escapeHtml($this->phonesms_config['shop_phone_sms']['alidayu_payment_order_template_id']); ?>" class="span3">
                        </div>
                    </div>
                    <div class="control-group dbshop-sms" style="display: none;">
                        <label for="input01" class="control-label"><?php echo $this->translate('发货完成模板ID'); ?>：</label>
                        <div class="controls">
                            <input type="text" name="alidayu_ship_order_template_id" id="alidayu_ship_order_template_id" value="<?php if(isset($this->phonesms_config['shop_phone_sms']['alidayu_ship_order_template_id'])) echo $this->escapeHtml($this->phonesms_config['shop_phone_sms']['alidayu_ship_order_template_id']); ?>" class="span3">
                        </div>
                    </div>
                    <div class="control-group dbshop-sms" style="display: none;">
                        <label for="input01" class="control-label"><?php echo $this->translate('确认收货模板ID'); ?>：</label>
                        <div class="controls">
                            <input type="text" name="alidayu_finish_order_template_id" id="alidayu_finish_order_template_id" value="<?php if(isset($this->phonesms_config['shop_phone_sms']['alidayu_finish_order_template_id'])) echo $this->escapeHtml($this->phonesms_config['shop_phone_sms']['alidayu_finish_order_template_id']); ?>" class="span3">
                        </div>
                    </div>
                    <div class="control-group dbshop-sms" style="display: none;">
                        <label for="input01" class="control-label"><?php echo $this->translate('订单取消模板ID'); ?>：</label>
                        <div class="controls">
                            <input type="text" name="alidayu_cancel_order_template_id" id="alidayu_cancel_order_template_id" value="<?php if(isset($this->phonesms_config['shop_phone_sms']['alidayu_cancel_order_template_id'])) echo $this->escapeHtml($this->phonesms_config['shop_phone_sms']['alidayu_cancel_order_template_id']); ?>" class="span3">
                        </div>
                    </div>
                    <hr>
                    <div class="control-group dbshop-sms" style="display: none;">
                        <label for="input01" class="control-label"><?php echo $this->translate('商品缺货提醒模板ID'); ?>：</label>
                        <div class="controls">
                            <input type="text" name="alidayu_goods_stock_template_id" id="alidayu_goods_stock_template_id" value="<?php if(isset($this->phonesms_config['shop_phone_sms']['alidayu_goods_stock_template_id'])) echo $this->escapeHtml($this->phonesms_config['shop_phone_sms']['alidayu_goods_stock_template_id']); ?>" class="span3">
                            <span class="alidayu" style="display: none;"><strong>${shopname} <?php echo $this->translate('店铺名称'); ?>、${goodsname} <?php echo $this->translate('商品名称'); ?>、${goodsstock} <?php echo $this->translate('当前商品库存数'); ?></strong>&nbsp;&nbsp;(<?php echo $this->translate('当商品库存数，达到商品管理中的商品缺货数量时，触发此模板'); ?>)</span>
                            <span class="qq-cloud"  style="display: none;"><strong>{1} <?php echo $this->translate('店铺名称'); ?>、{2} <?php echo $this->translate('商品名称'); ?>、{3} <?php echo $this->translate('当前商品库存数'); ?></strong>&nbsp;&nbsp;(<?php echo $this->translate('当商品库存数，达到商品管理中的商品缺货数量时，触发此模板'); ?>)</span>
                        </div>
                    </div>
                    <div class="control-group dbshop-sms" style="display: none;">
                        <label for="input01" class="control-label"><?php echo $this->translate('虚拟商品发货模板ID'); ?>：</label>
                        <div class="controls">
                            <input type="text" name="alidayu_virtual_goods_send_template_id" id="alidayu_virtual_goods_send_template_id" value="<?php if(isset($this->phonesms_config['shop_phone_sms']['alidayu_virtual_goods_send_template_id'])) echo $this->escapeHtml($this->phonesms_config['shop_phone_sms']['alidayu_virtual_goods_send_template_id']); ?>" class="span3">
                            <span class="alidayu" style="display: none;"><strong>${shopname} <?php echo $this->translate('店铺名称'); ?>、${goodsname} <?php echo $this->translate('商品名称'); ?>、${virtualaccount} <?php echo $this->translate('虚拟商品账号'); ?>、${virtualpassword} <?php echo $this->translate('虚拟商品密码'); ?></strong></span>
                            <span class="qq-cloud"  style="display: none;"><strong>{1} <?php echo $this->translate('店铺名称'); ?>、{2} <?php echo $this->translate('商品名称'); ?>、{3} <?php echo $this->translate('虚拟商品账号'); ?>、{4} <?php echo $this->translate('虚拟商品密码'); ?></strong></span>
                        </div>
                    </div>
                    <hr>
                    <div class="control-group dbshop-sms" style="display: none;">
                        <label for="input01" class="control-label"><?php echo $this->translate('审核通过会员模板ID'); ?>：</label>
                        <div class="controls">
                            <input type="text" name="alidayu_user_audit_template_id" id="alidayu_user_audit_template_id" value="<?php if(isset($this->phonesms_config['shop_phone_sms']['alidayu_user_audit_template_id'])) echo $this->escapeHtml($this->phonesms_config['shop_phone_sms']['alidayu_user_audit_template_id']); ?>" class="span3">
                            <span class="alidayu" style="display: none;"><strong>${shopname} <?php echo $this->translate('店铺名称'); ?>、${username} <?php echo $this->translate('客户名称'); ?></strong>&nbsp;&nbsp;(<?php echo $this->translate('当后台客户设置为手动审核，后台审核通过用户时，触发此模板'); ?>)</span>
                            <span class="qq-cloud"  style="display: none;"><strong>{1} <?php echo $this->translate('店铺名称'); ?>、{2} <?php echo $this->translate('客户名称'); ?></strong>&nbsp;&nbsp;(<?php echo $this->translate('当后台客户设置为手动审核，后台审核通过用户时，触发此模板'); ?>)</span>
                        </div>
                    </div>
                    <div class="control-group dbshop-sms" style="display: none;">
                        <label for="input01" class="control-label"><?php echo $this->translate('找回密码模板ID'); ?>：</label>
                        <div class="controls">
                            <input type="text" name="alidayu_user_password_template_id" id="alidayu_user_password_template_id" value="<?php if(isset($this->phonesms_config['shop_phone_sms']['alidayu_user_password_template_id'])) echo $this->escapeHtml($this->phonesms_config['shop_phone_sms']['alidayu_user_password_template_id']); ?>" class="span3">
                            <span class="alidayu" style="display: none;"><strong>${code} <?php echo $this->translate('验证码'); ?></strong></span>
                            <span class="qq-cloud" style="display: none;"><strong>{1} <?php echo $this->translate('验证码'); ?></strong></span>
                        </div>
                    </div>
                    <hr>
                    <div class="control-group dbshop-sms" style="display: none;">
                        <label for="input01" class="control-label"><?php echo $this->translate('手机验证码模板ID'); ?>：</label>
                        <div class="controls">
                            <input type="text" name="alidayu_phone_captcha_template_id" id="alidayu_phone_captcha_template_id" value="<?php if(isset($this->phonesms_config['shop_phone_sms']['alidayu_phone_captcha_template_id'])) echo $this->escapeHtml($this->phonesms_config['shop_phone_sms']['alidayu_phone_captcha_template_id']); ?>" class="span3">
                            <span class="alidayu" style="display: none;"><strong> ${code} 验证码</strong> <font color="red"><?php echo $this->translate('使用手机验证码，要在 系统管理-》系统设置-》验证码设置 里开启手机短信验证码。'); ?></font></span>
                            <span class="qq-cloud" style="display: none;"><strong> {1} 验证码</strong> <font color="red"><?php echo $this->translate('使用手机验证码，要在 系统管理-》系统设置-》验证码设置 里开启手机短信验证码。'); ?></font></span>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </form>
</div>
<script>
    <?php if ($this->success_msg != '') { ?>
    show_message('.message_one','<?php echo date("Y-m-d H:i:s"); ?>','<?php echo $this->success_msg; ?>','alert-success');
    <?php } ?>


    function select_phone_sms_type() {
        var phone_sms_type = $("#phone_sms_type").val();
        if(phone_sms_type == '') {
            $(".alidayu,.alidayu-msset,.aliyun-msset,.new-aliyun-msset,.aliyun-msset-info, .qq-cloud, .dbshop-sms").css('display', 'none');

        }
        if(phone_sms_type == 'alidayu') {
            $(".alidayu, .alidayu-msset, .dbshop-sms").css('display', '');
            $(".aliyun-msset, .new-aliyun-msset, .qq-cloud").css('display', 'none');
        }
        if(phone_sms_type == 'aliyun') {
            $(".alidayu, .aliyun-msset, .aliyun-msset-info, .dbshop-sms").css('display', '');
            $(".alidayu-msset, .new-aliyun-msset, .qq-cloud").css('display', 'none');
        }
        if(phone_sms_type == 'newaliyun') {
            $(".alidayu, .new-aliyun-msset, .aliyun-msset-info, .dbshop-sms").css('display', '');
            $(".aliyun-msset, .alidayu-msset, .qq-cloud").css('display', 'none');
        }
        if(phone_sms_type == 'qqCloud') {
            $(".alidayu,.alidayu-msset,.aliyun-msset,.new-aliyun-msset,.aliyun-msset-info").css('display', 'none');
            $(".qq-cloud, .dbshop-sms").css('display', '');
        }
    }
    <?php if(isset($this->phonesms_config['shop_phone_sms']['phone_sms_type']) and $this->phonesms_config['shop_phone_sms']['phone_sms_type'] != '') { ?>
    select_phone_sms_type();
    <?php } ?>
</script>