    		<div style="height:30px;border-bottom:4px solid #DFDFDF;">
        	<p class="pull-left" style="font-size:16px; line-height:30px;"><strong><?php echo $this->translate('管理文章'); ?> - (<?php echo $this->translate('文章数：').$this->article_list->getTotalItemCount(); ?>)</strong></p>
        	<p class="pull-right">
            <a href="<?php echo $this->url('cms/default',array('action'=>'add','controller'=>'cms')); ?>" class="btn btn-small btn-primary"><i class="icon-plus icon-white"></i> <?php echo $this->translate('添加文章'); ?></a>&nbsp;
            <a href="<?php echo $this->myviewalias()->dbshopHelpUrl('cms_set'); ?>" target="_blank" class="btn btn-small btn-info"><i class="icon-info-sign icon-white"></i> <?php echo $this->translate('查看帮助说明'); ?></a>
            </p>
        	</div>
            <table class="table table-hover">
            <thead style="background:#CCC;">
            	<tr>
                    <th width="5%">ID</th>
                    <th width="20%"><?php echo $this->translate('文章标题'); ?></th>
                    <th width="10%"><?php echo $this->translate('文章分类'); ?></th>
                    <th width="10%"><?php echo $this->translate('文章状态'); ?></th>
                    <th width="10%"><?php echo $this->translate('添加时间'); ?></th>
                    <th width="6%"><?php echo $this->translate('文章排序'); ?></th>
                    <th width="10%"><?php echo $this->translate('操作'); ?></th>
                </tr>
            </thead>
            <form method="GET" action="">
            <tr class="goods_search" style="background: #F5F5F5;">
            <td>
				<p>
					<?php echo $this->translate('始'); ?>
					<input type="text" name="start_article_id"
						value="<?php if ($this->searchArray and isset($this->searchArray['start_article_id'])) echo $this->searchArray['start_article_id']; ?>"
						 class="span8">
				</p>
				<p>
					<?php echo $this->translate('终'); ?>
					<input type="text" name="end_article_id"
						value="<?php if ($this->searchArray and isset($this->searchArray['end_article_id'])) echo $this->searchArray['end_article_id']; ?>"
						 class="span8">
				</p>
            </td>
            <td>
				<input type="text" name="article_title"
					value="<?php if ($this->searchArray and isset($this->searchArray['article_title'])) echo $this->searchArray['article_title']; ?>"
					 class="span11">
            </td>
            <td>
				<select name="article_class_id" class="span8">
					<option value=""><?php echo $this->translate('文章分类'); ?></option>
                                <?php 
								if ($this->article_class) {
                                	foreach ($this->article_class as $class_val) {
								?>
                                <option value="<?php echo $class_val['article_class_id'] ?>" <?php if(($this->searchArray and $this->searchArray['article_class_id'] == $class_val['article_class_id']) or ($class_val['article_class_id'] == $this->article_class_id)) { ?>selected="selected"<?php } ?>><?php echo str_repeat('&nbsp;', $class_val['class_level'] * 5).$class_val['article_class_name']; ?></option>
                                <?php
                                	}
                                }
								?>
				</select>
            </td>
            <td>
				<select name="article_state" class="span8">
					<option value=""><?php echo $this->translate('文章状态'); ?></option>
					<option value="1"
						<?php if($this->searchArray and isset($this->searchArray['article_state']) and $this->searchArray['article_state']!='' and $this->searchArray['article_state'] == 1) echo 'selected="selected"'; ?>><?php echo $this->translate('已启用'); ?></option>
					<option value="0"
						<?php if($this->searchArray and isset($this->searchArray['article_state']) and $this->searchArray['article_state']!='' and $this->searchArray['article_state'] == 0) echo 'selected="selected"'; ?>><?php echo $this->translate('已禁用'); ?></option>
				</select>
            </td>
            <td>
            <p><?php echo $this->translate('始'); ?><input type="text" name="search_start_time" id="search_start_time" value="<?php if ($this->searchArray and isset($this->searchArray['search_start_time'])) echo $this->searchArray['search_start_time']; ?>" onclick="WdatePicker({el:'search_start_time'})"  class="span8"></p><p><?php echo $this->translate('终'); ?><input type="text" name="search_end_time" id="search_end_time" value="<?php if ($this->searchArray and isset($this->searchArray['search_end_time'])) echo $this->searchArray['search_end_time']; ?>" onclick="WdatePicker({el:'search_end_time'})" class="span8"></p>
            </td>
            <td>
            </td>
            <td>
                    <p><button class="btn btn-small btn-primary" type="submit"><i class="icon-search icon-white"></i> <?php echo $this->translate('搜索'); ?></button></p>
                    <?php if ($this->searchArray and !empty($this->searchArray)) { ?>
                    <p><a href="<?php echo $this->url('cms/default'); ?>" class="btn btn-small"><i class="icon-arrow-left"></i> <?php echo $this->translate('返回'); ?></a></p>
                    <?php } ?>
            </td>
            </tr>
            </form>
            <form action="<?php echo $this->url('cms/default/article_page',array('action'=>'allArticleUpdate','controller'=>'cms','page'=>$this->page), array('query'=>$this->query)); ?>" name="article_form" id="article_form" method="post">
            <?php
			if ($this->article_list) {
				foreach ($this->article_list as $article_val) {
			?>            
            <tr>
            	<td><?php echo $article_val['article_id']; ?></td>
            	<td><?php echo $this->escapeHtml($article_val['article_title']); ?></td>
                <td><?php echo $this->escapeHtml($article_val['article_class_name']); ?></td>
                <td><?php echo ($article_val['article_state'] == 1 ? $this->translate('启用') : $this->translate('禁用')); ?></td>
                <td><?php echo date('Y-m-d H:i',$article_val['article_add_time']); ?></td>
                <td><input type="text" class="span8" name="article_sort[<?php echo $article_val['article_id']; ?>]" value="<?php echo $article_val['article_sort']; ?>"></td>
                <td><a href="<?php echo $this->url('cms/default/article_id',array('action'=>'edit','controller'=>'cms','article_id'=>$article_val['article_id'], 'page'=>$this->page), array('query'=>$this->query)); ?>"><?php echo $this->translate('编辑'); ?></a>
                <span>|</span>
                <a href="javascript:;" onclick="return article_del_js(<?php echo $article_val['article_id']; ?>);"><?php echo $this->translate('删除'); ?></a>
                <span>|</span>
                <a target="_blank" href="<?php echo $this->url('frontarticle/default/cms_id',array('action'=>'content','cms_id'=>$article_val['article_id'])); ?>"><?php echo $this->translate('文章预览'); ?></a>
                </td>  
            </tr>
            <?php
				}
			}
			?>
            <tr>
			<td colspan="7" style="background: #FFF">
                <div class="pull-left span6" style="height: 30px; line-height: 30px;">
                    <button type="submit" class="btn btn-small btn-primary"><i class="icon-tasks icon-white"></i> <?php echo $this->translate('批量修改'); ?></button>
                </div>
				<?php echo ( count($this->article_list) > 0 ) ? $this->paginationControl($this->article_list, 'Sliding', 'common/pager',array('page_url'=>$this->url('cms/default/article_page',array('action'=>'index','controller'=>'cms')))) : ""; ?>
                </td>
		    </tr>
            </form>
            </table>

<script src="<?php echo $this->basePath('/public/js/DatePicker/WdatePicker.js'); ?>"></script>  
<script>
//文章删除js
function article_del_js(article_id) {
	if(window.confirm('<?php echo $this->translate('您确实要删除该文章吗？'); ?>')) {
	$.post("<?php echo $this->url('cms/default',array('action'=>'del','controller'=>'cms')); ?>",{article_id:article_id},
	function(data){
		if(data != 'false') {
			window.location.href='<?php echo $this->url('cms/default/article_page',array('action'=>'index','controller'=>'cms','page'=>$this->page), array('query'=>$this->query)); ?>';
			return true;
		} else {
			alert('<?php echo $this->translate('文章删除失败！'); ?>');
		}
	});
	}
	return false;
}
</script>