    		<div id="sticky_navigation" style="height:30px;border-bottom:4px solid #DFDFDF;">
        	<p class="pull-left" style="font-size:16px; line-height:30px;"><strong><?php echo $this->translate('商品品牌'); ?></strong>&nbsp;&nbsp;|&nbsp;&nbsp;<small><?php echo $this->translate('前台添加商品品牌导航'); ?> <a href="<?php echo $this->url('navigation/default'); ?>"><?php echo $this->translate('请点击这里'); ?></a></small></p>
        	<p class="pull-right">
        	<a href="<?php echo $this->url('brand/default',array('action'=>'add','controller'=>'brand')); ?>" class="btn btn-small btn-primary"><i class="icon-plus icon-white"></i> <?php echo $this->translate('添加品牌'); ?></a>&nbsp;
        	<a href="<?php echo $this->myviewalias()->dbshopHelpUrl('goods_brand_set'); ?>" target="_blank" class="btn btn-small btn-info"><i class="icon-info-sign icon-white"></i> <?php echo $this->translate('查看帮助说明'); ?></a>
        	</p>
        	</div>
            <form action="<?php echo $this->url('brand/default',array('action'=>'allBrandUpdate','controller'=>'brand')); ?>" name="submit_form" id="submit_form" method="post">
            <table class="table table-hover">
            <thead style="background:#CCC;">
            	<tr>
                    <th width="45%"><?php echo $this->translate('品牌名称 (品牌ID)'); ?></th>
                    <th width="20%"><?php echo $this->translate('品牌图片'); ?></th>
                    <th width="15%"><?php echo $this->translate('商品数量'); ?></th>
                    <th width="10%"><?php echo $this->translate('排序'); ?></th>
                    <th width="10%"><?php echo $this->translate('操作'); ?></th>
                </tr>
            </thead>
            <?php
			if ($this->brand_array) {
				foreach ($this->brand_array as $brand_val) {
			?>
            <tr>
            	<td style="vertical-align:middle"><?php echo $this->escapeHtml($brand_val['brand_name']); ?> (ID:<?php echo $brand_val['brand_id']; ?>)</td>
            	<td><?php if ($brand_val['brand_logo'] != '') { ?> <img src="<?php echo $this->basePath($brand_val['brand_logo']); ?>" border="0" width="80" height="30" /><?php } else { echo $this->translate('暂无LOGO'); } ?></td>
            	<td style="vertical-align:middle"><?php echo $brand_val['goods_num']; ?></td>
                <td style="vertical-align:middle"><input type="text" class="span8" name="brand_sort[<?php echo $brand_val['brand_id']; ?>]" value="<?php echo $brand_val['brand_sort']; ?>"></td>
            	<td style="vertical-align:middle">
                    <a href="<?php echo $this->url('brand/default',array('action'=>'edit','controller'=>'brand','brand_id'=>$brand_val['brand_id']),null,true); ?>"><?php echo $this->translate('编辑'); ?></a>
                    <span>|</span>
                    <a href="javascript:;" onclick="return brand_del_js(<?php echo $brand_val['brand_id']; ?>);"><?php echo $this->translate('删除'); ?></a>
                </td>  
            </tr>
            <?php
				}
            ?>
                <tr>
                    <td colspan="5" style="background: #FFF">
                        <div class="pull-left span6" style="height: 30px; line-height: 30px;">
                            <button type="submit" class="btn btn-small btn-primary"><i class="icon-tasks icon-white"></i> <?php echo $this->translate('批量修改'); ?></button>
                        </div>
                    </td>
                </tr>
			<?php } else {
			?>
			<tr><td colspan="5"><?php echo $this->translate('暂无商品品牌'); ?></td></tr>
			<?php } ?> 
            </table>
            </form>
<script>
//品牌删除操作js
function brand_del_js(brand_id) {
	if(window.confirm('<?php echo $this->translate('您确实要删除该品牌吗？'); ?>')) {
	$.post("<?php echo $this->url('brand/default',array('action'=>'del','controller'=>'brand')); ?>",{brand_id:brand_id},
	function(data){
		if(data != 'false') {
			window.location.href='<?php echo $this->url('brand/default',array('action'=>'index','controller'=>'brand')); ?>';
			return true;
		} else {
			alert('<?php echo $this->translate('品牌删除失败！'); ?>');
		}
	});
	}
	return false;
}
</script>