<div class="row-fluid" style="margin-top:20px;">
  <?php echo $this->partial('shopfront/home/left_menu.phtml'); ?>
  <div class="span8" id="home_goods_order">
  	<div class="well">
    	<h5><?php echo $this->translate('我的收藏'); ?></h5>
            <table class="table table-bordered">
            	<thead>
                	<tr class="home-user-tr">
                    	<th width="80%"><?php echo $this->translate('商品信息'); ?></th>
                        <th width="20%"><?php echo $this->translate('操作'); ?></th>
                    </tr>
                </thead>
                <?php if ($this->favorites_list->getTotalItemCount() > 0) { foreach ($this->favorites_list as $favorites_value) { ?>
               	<tr>
                	<td><a href="<?php echo $this->url('frontgoods/default', array('goods_id'=>$favorites_value['goods_id'], 'class_id'=>$favorites_value['class_id'])); ?>" target="_blank"><img src="<?php echo $this->basePath($this->frontwebsite()->shopGoodsImage($favorites_value['goods_thumbnail_image'])); ?>"  style=" height:65px;width:65px;border:1px solid #D7D7D7"></a>&nbsp;&nbsp;<a href="<?php echo $this->url('frontgoods/default', array('goods_id'=>$favorites_value['goods_id'], 'class_id'=>$favorites_value['class_id'])); ?>" target="_blank"><?php echo $this->escapeHtml($favorites_value['goods_name']); ?></a></td>
                    <td><a href="<?php echo $this->url('frontfavorites/default/favorites_id', array('action'=>'del','favorites_id'=>$favorites_value['favorites_id'])); ?>" onclick="return window.confirm('<?php echo $this->translate('您确实要删除该收藏商品吗？'); ?>');"><?php echo $this->translate('删除'); ?></a></td>
                </tr>
                <?php } } else { ?>
                <tr>
                	<td colspan="2"><?php echo $this->translate('暂无商品收藏！'); ?></td>
                </tr>
                <?php } ?>
                    <tr>
                    <td colspan="2">
        		<?php echo ( count($this->favorites_list) > 0 ) ? $this->paginationControl($this->favorites_list, 'Sliding', 'site/dbpage',array('page_url'=>$this->url('frontfavorites/default/favorites_page', array('action'=>'index')))) : ""; ?>
                    </td>
                    </tr>
    		</table>
    </div>
  </div>
</div>