<div class="row-fluid" style="margin-top:20px;">
    <?php echo $this->partial('shopfront/home/left_menu.phtml'); ?>
    <div class="span8">
        <div class="well">
            <div class="span12">
                <div class="span6">
                    <h5><?php echo $this->title_name; ?></h5>
                </div>
            </div>
            <?php echo $this->partial($this->partial_template_file); ?>
        </div>
    </div>
</div>