    <a href="<?php echo $this->url('frontmoney/default'); ?>" <?php if($this->myviewalias()->returnActionname() == 'index') echo 'class="current"'; ?>><?php echo $this->translate('账户余额记录'); ?></a>
    <span class="sep">|</span>
    <a href="<?php echo $this->url('frontmoney/default', array('action'=>'paylog')); ?>" <?php if($this->myviewalias()->returnActionname() == 'paylog') echo 'class="current"'; ?>><?php echo $this->translate('账户消费记录'); ?></a>
    <span class="sep">|</span>
    <a href="<?php echo $this->url('frontmoney/default', array('action'=>'paychecklog')); ?>" <?php if($this->myviewalias()->returnActionname() == 'paychecklog') echo 'class="current"'; ?>><?php echo $this->translate('账户充值记录'); ?></a>
    <span class="sep">|</span>
    <a href="<?php echo $this->url('frontmoney/default', array('action'=>'withdrawlog')); ?>" <?php if($this->myviewalias()->returnActionname() == 'withdrawlog') echo 'class="current"'; ?>><?php echo $this->translate('账户提现记录'); ?></a>
    <span class="sep">|</span>
    <a href="<?php echo $this->url('frontmoney/default', array('action'=>'refundlog')); ?>" <?php if($this->myviewalias()->returnActionname() == 'refundlog') echo 'class="current"'; ?>><?php echo $this->translate('账户退款记录'); ?></a>