<div class="header_menu">
    <div class="container">
        <div class="header-nav clearfix">
            <?php echo $this->partial('site/headermenu'); ?>
        </div>
    </div>
</div>
</div>
<div class="container breadcrumbs">
    <a href="<?php echo $this->url('shopfront/default'); ?>"><?php echo $this->translate('首页'); ?></a>
    <span class="sep">/</span><span><?php echo $this->translate('中心首页'); ?></span>
</div>

<div class="container">
<div class="uc-full-box">
    <div class="row">
        <div class="span4">
            <?php echo $this->partial('shopfront/home/left_menu.phtml'); ?>
        </div>
        <!-- .span4 END -->

        <div class="span16">
            <div class="xm-box uc-box">

                <div class="xm-line-box uc-info-box">
                    <div class="box-bd clearfix">
                        <img alt="" src="<?php echo $this->basePath($this->frontwebsite()->getUserSession('user_avatar')); ?>" class="uc-avatar">
                        <div class="uc-info">
                            <h3 class="uc-welcome"><span class="user-name"><a href="<?php echo $this->url('fronthome/default', array('action'=>'useredit')); ?>"><?php echo $this->frontwebsite()->getUserSession('user_name'); ?></a></span></h3>
                            <div class="uc-info-detail">
                                <div class="info-notice">
                                    <?php echo $this->translate('用户等级'); ?>：<?php echo $this->frontwebsite()->getUserSession('user_group_name'); ?>
                                    <span class="sep">|</span>
                                    <?php echo $this->translate('账户余额'); ?>：<?php echo $this->frontwebsite()->shopPriceExtend($this->user_info->user_money); ?> <a href="<?php echo $this->url('frontmoney/default'); ?>" class="btn btn-small btn-primary" style="width: 50px;height:"><?php echo $this->translate('充值'); ?></a>
                                    <span class="sep">|</span>
                                    <?php echo $this->translate('消费积分'); ?>：<?php echo $this->user_info->user_integral_num; ?>
                                    <span class="sep">|</span>
                                    <?php echo $this->translate('等级积分'); ?>：<?php echo $this->user_info->integral_type_2_num; ?>
                                    <br>
                                    <?php echo $this->translate('用户提醒'); ?>：
                                    <a href="<?php echo $this->url('frontorder/default/order_state', array('action'=>'index', 'order_state'=>10)); ?>"><span class="badge <?php if($this->order_state_num[10]>0) echo 'badge-important'; ?>"><?php echo $this->translate('待支付订单'); ?>(<?php echo $this->order_state_num[10]; ?>)</span></a>&nbsp;&nbsp;
                                    <a href="<?php echo $this->url('frontorder/default/order_state', array('action'=>'index', 'order_state'=>30)); ?>"><span class="badge <?php if($this->order_state_num[30]>0) echo 'badge-important'; ?>"><?php echo $this->translate('待发货订单'); ?>(<?php echo $this->order_state_num[30]; ?>)</span></a>&nbsp;&nbsp;
                                    <a href="<?php echo $this->url('frontorder/default/order_state', array('action'=>'index', 'order_state'=>40)); ?>"><span class="badge <?php if($this->order_state_num[40]>0) echo 'badge-important'; ?>"><?php echo $this->translate('已发货订单'); ?>(<?php echo $this->order_state_num[40]; ?>)</span></a>
                                </div>
                                <div class="info-goods">
                                    <!--
                                    <a href="#">新品上架（??）</a>
                                    <span class="sep">|</span>
                                    <a href="#">收藏商品降价（?）</a>
                                    <span class="sep">|</span>
                                    <a href="#">待评价商品（?）</a>
                                    <span class="sep">|</span>
                                    <a href="#">发现商品</a>
                                    -->
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- <div class="xm-line-box uc-home-box">
                    <div class="box-hd">
                        <h3 class="title">未支付订单</h3>
                    </div>
                </div> -->

            </div>

            <div class="uc-box">
            <div class="uc-order-list-box">
            <ul class="uc-order-detail-list">
                <?php if($this->order_list) {
                foreach ($this->order_list as $order_value) {
                $i = 0;
                $goodsArray = unserialize($order_value['goods_serialize']);
                $rowspan    = count($goodsArray);
                ?>
            <li class="uc-order-detail-item">
                <table class="order-detail-table">
                    <thead>
                    <tr>
                        <th colspan="3" class="column-info column-t">
                            <div class="column-content">
                                <span class="order-status"><?php echo $this->frontwebsite()->getOneOrderStateInfo($order_value['order_state']); ?></span>
                                <?php echo $this->translate('订单编号'); ?>：<a href="<?php echo $this->url('frontorder/default/order_id', array('action'=>'showorder', 'order_id'=>$order_value['order_id'], 'order_state'=>$order_value['order_state'])); ?>"><?php echo $order_value['order_sn']; ?></a>
                                <span class="sep">|</span>
                                <?php echo $this->escapeHtml($order_value['buyer_name']); ?>
                                <span class="sep">|</span>
                                <?php echo date("Y-m-d H:i:s",$order_value['order_time']); ?>
                            </div>
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td class="column-detail column-l">
                            <ul class="order-goods-list">
                                <?php if(is_array($goodsArray) and !empty($goodsArray)) foreach($goodsArray as $goods_key => $goods_value) { ?>
                                <li <?php if($i == 0) echo 'class="first"'; ?>>
                                    <a href="<?php echo $this->url('frontgoods/default', array('goods_id'=>$goods_value['goods_id'], 'class_id'=>$goods_value['class_id'])); ?>" target="_blank">
                                        <img alt="<?php echo strip_tags($goods_value['goods_name']); ?>" title="<?php echo strip_tags($goods_value['goods_name']); ?>" src="<?php echo $this->basePath($this->frontwebsite()->shopGoodsImage($goods_value['goods_image'])); ?>" class="goods-thumb">
                                    </a>
                                    <a class="goods-name" href="<?php echo $this->url('frontgoods/default', array('goods_id'=>$goods_value['goods_id'], 'class_id'=>$goods_value['class_id'])); ?>" target="_blank"><?php echo strip_tags($goods_value['goods_name']); ?></a>
                                    <span class="goods-price"><?php echo $order_value['currency_symbol'] . $order_value['order_amount'] . $order_value['currency_unit']; ?></span>
                                    <span><?php echo strip_tags($goods_value['goods_extend_info']); ?></span>
                                </li>
                                <?php $i++; } ?>
                            </ul>
                        </td>
                        <td class="column-price">
                            <div class="order-info order-price"><?php echo $order_value['currency_symbol'] . $order_value['order_amount'] . $order_value['currency_unit']; ?></div>
                        </td>
                        <td class="column-action column-r">
                            <div class="order-info order-action">
                                <a href="<?php echo $this->url('frontorder/default/order_id', array('action'=>'showorder', 'order_id'=>$order_value['order_id'], 'order_state'=>$order_value['order_state'])); ?>"><?php echo $this->translate('订单详情'); ?><i class="iconfont"></i></a>
                            </div>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </li>
                <?php } } ?>
            </ul>
            </div>
            </div>
        </div>
    </div>

</div>
<!-- .uc-full-box END -->


</div>