
        </div>
    </div>
</div>
<div class='footer'>
    <p align="center" style=" padding-top:8px;padding-bottom:8px;"><?php echo sprintf($this->translate('Copyright %s%s 版权所有'), '&copy; ',DBSHOP_YEAR_COPYRIGHT . ' <a href="'.(defined('DBSHOP_ADMIN_COPYRIGHT_URL') ? DBSHOP_ADMIN_COPYRIGHT_URL : 'http://www.dbshop.net/').'" target="_blank" style="color:#FFF">'.(defined('DBSHOP_ADMIN_COPYRIGHT') ? DBSHOP_ADMIN_COPYRIGHT : 'DBShop').'</a>'); ?></p>
</div>