<?php if ($this->dbTongJiPage == 'index') { ?>
<header class="ect-header ect-margin-tb ect-margin-lr"> <a href="<?php echo $this->url('m_class/default'); ?>" class="pull-left ect-icon ect-icon1 ect-icon-cate1"></a>
    <div class="ect-header-div">
        <button class="btn btn-default ect-text-left ect-btn-search" onClick="javascript:openSearch();"><i class="fa fa-search"></i>&nbsp;<?php echo $this->translate('简单搜索'); ?></button>
    </div>
</header>
<?php } elseif ($this->dbTongJiPage == 'goods_class' or $this->dbTongJiPage == 'goods_search') { ?>
    <div style="height:7.2em;"></div>
    <header>
        <nav class="ect-nav ect-bg icon-write">
            <ul class="ect-diaplay-box text-center">
                <li class="ect-box-flex"><a href="<?php echo $this->url('mobile/default'); ?>"><i class="ect-icon ect-icon-home"></i><?php echo $this->translate('首页'); ?></a></li>
                <li class="ect-box-flex"><a href="<?php echo $this->url('m_class/default'); ?>"><i class="ect-icon ect-icon-cate"></i><?php echo $this->translate('分类'); ?></a></li>
                <li class="ect-box-flex"><a href="javascript:openSearch();"><i class="ect-icon ect-icon-search"></i><?php echo $this->translate('搜索'); ?></a></li>
                <li class="ect-box-flex"><a href="<?php echo $this->url('m_cart/default'); ?>"><i class="ect-icon ect-icon-flow"></i><?php echo $this->translate('购物车'); ?></a></li>
                <li class="ect-box-flex"><a href="<?php echo $this->url('m_home/default'); ?>"><i class="ect-icon ect-icon-user"></i><?php echo $this->translate('用户中心'); ?></a></li>
            </ul>
        </nav>
    </header>
<?php } elseif ($this->dbTongJiPage != 'class_list')  { ?>
    <div class="ect-bg">
        <header class="ect-header ect-margin-tb ect-margin-lr text-center icon-write ect-bg">
            <?php if($this->dbTongJiPage != 'cartSubmit') { ?>
            <a href="javascript:history.go(-1)" class="pull-left ect-icon ect-icon1 ect-icon-history"></a>
            <?php } ?>
            <span><?php echo ($this->dbTongJiPage == 'goods_body' ? $this->mobile_title_name : $this->title_name); ?></span> <a href="javascript:;"  onClick="openMune()" class="pull-right ect-icon ect-icon1 ect-icon-mune icon-write"></a></header>
        <nav class="ect-nav ect-nav-list" style="display:none;">
            <ul class="ect-diaplay-box text-center">
                <li class="ect-box-flex"><a href="<?php echo $this->url('mobile/default'); ?>"><i class="ect-icon ect-icon-home"></i><?php echo $this->translate('首页'); ?></a></li>
                <li class="ect-box-flex"><a href="<?php echo $this->url('m_class/default'); ?>"><i class="ect-icon ect-icon-cate"></i><?php echo $this->translate('分类'); ?></a></li>
                <li class="ect-box-flex"><a href="javascript:openSearch();"><i class="ect-icon ect-icon-search"></i><?php echo $this->translate('搜索'); ?></a></li>
                <li class="ect-box-flex"><a href="<?php echo $this->url('m_cart/default'); ?>"><i class="ect-icon ect-icon-flow"></i><?php echo $this->translate('购物车'); ?></a></li>
                <li class="ect-box-flex"><a href="<?php echo $this->url('m_home/default'); ?>"><i class="ect-icon ect-icon-user"></i><?php echo $this->translate('用户中心'); ?></a></li>
            </ul>
        </nav>
    </div>
<?php } ?>