<div style="height:30px;border-bottom:4px solid #DFDFDF;margin-bottom:10px;">
  <p class="pull-left" style="font-size:16px; line-height:30px;"><strong><?php echo $this->translate('手动更新下载操作'); ?></strong></p>
  <p class="pull-right"> <a href="<?php echo $this->url('package/default'); ?>" class="btn btn-small"><i class="icon-arrow-left"></i> <?php echo $this->translate('返回系统更新列表'); ?></a>&nbsp; <a href="<?php echo $this->myviewalias()->dbshopHelpUrl('online_package'); ?>" target="_blank" class="btn btn-small btn-info"><i class="icon-info-sign icon-white"></i> <?php echo $this->translate('查看帮助说明'); ?></a></p>
</div>
<div class="alert alert-error" id="warning_info"> <strong><?php echo $this->translate('建议您在更新前，备份相关的程序及数据信息，以免更新失败给您造成不必要的损失。'); ?></strong> </div>
<div>
<table class="table table-bordered">
    <tr>
      <td width="15%" style="background-color:#999;color:#FFF;"><strong><?php echo $this->translate('更新名称'); ?></strong></td>
      <td><?php echo (isset($this->packageInfo->update_name) and $this->packageInfo->update_name != '') ? $this->packageInfo->update_name : '&nbsp;'; ?></td>
    </tr>
    <tr>
      <td width="15%" style="background-color:#999;color:#FFF;"><strong><?php echo $this->translate('更新包版本'); ?></strong></td>
      <td><?php echo (isset($this->packageInfo->version_name) and $this->packageInfo->version_name != '') ? $this->packageInfo->version_name : '&nbsp;'; ?></td>
    </tr>
    <tr>
      <td width="15%" style="background-color:#999;color:#FFF;"><strong><?php echo $this->translate('MD5校验值'); ?></strong></td>
      <td><?php echo ($this->php_version_str == 'PHP5.4_' ? $this->packageInfo->package_md5 : $this->packageInfo->package_md5_54); ?>&nbsp;&nbsp;&nbsp;&nbsp;(<strong><?php echo $this->translate('无大小写区分'); ?></strong>)</td>
    </tr>
    <tr>
      <td width="15%" style="background-color:#999;color:#FFF;"><strong><?php echo $this->translate('更新描述'); ?></strong></td>
      <td>
          <div style="height: 500px;overflow: auto;">
              <style>
                  p {margin-bottom: 3px;font-size: 15px;}
              </style>
          <?php echo (isset($this->packageInfo->update_info) and $this->packageInfo->update_info != '') ? $this->packageInfo->update_info : '&nbsp;'; ?>
        </div>
      </td>
    </tr>
    <tr>
      <td width="15%" style="background-color:#999;color:#FFF;"><strong><?php echo $this->translate('特别提醒'); ?></strong></td>
      <td><strong style="font-size:14px; color:#F00;"><?php echo $this->translate('当下载的更新包中有sql文件时，请先将sql目录中的内容更新到数据库中（如更新包中无sql目录，无需更新数据库），然后再把除sql目录外的其他目录覆盖到程序目录,覆盖完成后，把/data/cache/modulecache/目录中的所有文件删除，更新至此完成。'); ?></strong></td>
    </tr>
  </table>
</div>
<div class="text-center" style="margin-bottom:20px;">
    <a href="<?php echo $this->packageInfo->package_download_url.$this->packageInfo->update_package; ?>" class="btn btn-large btn-primary"><?php echo $this->translate('点击下载更新包'); ?></a>
</div>
