    		<div id="sticky_navigation" style="height:30px;border-bottom:4px solid #DFDFDF;">
        	<p class="pull-left" style="font-size:16px; line-height:30px;"><strong><?php echo $this->translate('管理客户组'); ?></strong></p>
        	<p class="pull-right">
            <a href="<?php echo $this->url('usergroup/default',array('action'=>'add','controller'=>'usergroup')); ?>" class="btn btn-small btn-primary"><i class="icon-plus icon-white"></i> <?php echo $this->translate('添加客户组'); ?></a>&nbsp;
            <a href="<?php echo $this->myviewalias()->dbshopHelpUrl('user_group_set'); ?>" target="_blank" class="btn btn-small btn-info"><i class="icon-info-sign icon-white"></i> <?php echo $this->translate('查看帮助说明'); ?></a>
            </p>
        	</div>
            <table class="table table-hover">
            <thead style="background:#CCC;">
            	<tr>
                    <th width="5%">ID</th>
                    <th width="30%"><?php echo $this->translate('客户组名称'); ?></th>
                    <th width="35%"><?php echo $this->translate('等级积分范围'); ?></th>
                    <th width="20%"><?php echo $this->translate('等级积分状态'); ?></th>
                    <th width="10%"><?php echo $this->translate('操作'); ?></th>
                </tr>
            </thead>
            <?php
			if ($this->group_array) {
				foreach ($this->group_array as $group_val) {
			?>            
            <tr>
            	<td><?php echo $group_val['group_id']; ?></td>
				<td><?php echo $this->escapeHtml($group_val['group_name']); ?></td>
            	<td><?php echo $group_val['integral_num_start'] . ' ~ ' . $group_val['integral_num_end']; ?></td>
            	<td><?php echo ($group_val['integral_num_state'] == 1 ? $this->translate('启用') : $this->translate('关闭')); ?></td>
            	<td><a href="<?php echo $this->url('usergroup/default/user_group_id',array('action'=>'edit','controller'=>'usergroup','user_group_id'=>$group_val['group_id'])); ?>"><?php echo $this->translate('编辑'); ?></a><?php if ($group_val['group_id'] != 1) { ?><span>|</span><a href="javascript:;" onclick="return group_del_js(<?php echo $group_val['group_id']; ?>);"><?php echo $this->translate('删除'); ?></a><?php } ?></td>  
            </tr>
            <?php
				}
			}
			?>
            </table>
            
<script>
//客户组删除js
function group_del_js(group_id) {
	if(window.confirm('<?php echo $this->translate('您确实要删除该客户组吗？'); ?>')) {
	$.post("<?php echo $this->url('usergroup/default',array('action'=>'del','controller'=>'usergroup')); ?>",{group_id:group_id},
	function(data){
		if(data != 'false') {
			window.location.href='<?php echo $this->url('usergroup/default',array('action'=>'index','controller'=>'usergroup')); ?>';
			return true;
		} else {
			alert('<?php echo $this->translate('客户组删除失败，该客户组下已经有客户存在，需要先删除组下客户信息！'); ?>');
		}
	});
	}
	return false;
}
</script>