<link rel="stylesheet" href="<?php echo $this->basePath('public/mobile/default/css/touch.css'); ?>">
<div class="ect-margin-tb ect-pro-list ect-margin-bottom0 ect-border-bottom0">
    <ul>
        <?php if ($this->favorites_list->getTotalItemCount() > 0) { foreach ($this->favorites_list as $favorites_value) { ?>
        <li class="single_item"> <a target="_blank" href="<?php echo $this->url('m_goods/default', array('goods_id'=>$favorites_value['goods_id'], 'class_id'=>$favorites_value['class_id'])); ?>"><img src="<?php echo $this->basePath($this->frontwebsite()->shopGoodsImage($favorites_value['goods_thumbnail_image'])); ?>"></a>
            <dl>
                <dt>
                <h4 class="title"><a target="_blank" href="<?php echo $this->url('m_goods/default', array('goods_id'=>$favorites_value['goods_id'], 'class_id'=>$favorites_value['class_id'])); ?>"><?php echo $this->escapeHtml($favorites_value['goods_name']); ?></a></h4>
                </dt>
                <dd style="height: 20px;"></dd>
                <dd class="text-center">
                    <a href="<?php echo $this->url('m_favorites/default/favorites_id', array('action'=>'del','favorites_id'=>$favorites_value['favorites_id'])); ?>" onclick="return window.confirm('<?php echo $this->translate('您确实要删除该收藏商品吗？'); ?>');" class="flow-del"><?php echo $this->translate('删除'); ?></a>
                </dd>
            </dl>
        </li>
        <?php } ?>
            <p>
                <?php echo ( count($this->favorites_list) > 0 ) ? $this->paginationControl($this->favorites_list, 'Sliding', 'mobile/page',array('page_url'=>$this->url('m_favorites/default/favorites_page', array('action'=>'index')))) : ""; ?>
            </p>
        <?php } else { ?>
        <p class="text-center ect-margin-tb ect-padding-tb"><?php echo $this->translate('暂无商品收藏信息'); ?></p>
        <?php } ?>
    </ul>

</div>