<section class="flow-consignee ect-bg-colorf">
    <p style="text-align: center">
       <img src="<?php echo  $this->basePath($this->frontwebsite()->createQRcode($this->url('mobile/default', array(), array('force_canonical'=>true, 'query'=>array('user_id'=>$this->frontwebsite()->getUserSession('user_id')))), $this->frontwebsite()->getUserSession('user_id'), 'invitation')); ?>" />
    </p>
    <p style="text-align: center">
        <?php echo $this->translate('长按二维码，进行保存或者分享给好友'); ?>
    </p>
</section>