<div style="border-bottom:none;" class="ect-pro-list user-order">
    <ul>
        <?php if ($this->order_list->getTotalItemCount() > 0) { ?>
            <?php foreach ($this->order_list as $order_value) {
                $goodsArray = current(unserialize($order_value['goods_serialize']));
                ?>
            <li class="single_item">
            <a href="<?php echo $this->url('m_order/default/order_id', array('action'=>'showorder', 'order_id'=>$order_value['order_id'], 'order_state'=>$order_value['order_state'], 'page'=>$this->page)); ?>"><img class="pull-left" src="<?php echo $this->basePath($this->frontwebsite()->shopGoodsImage($goodsArray['goods_image'])); ?>">
                <dl>
                    <dt>
                    <h4 class="title"><?php echo $this->translate('订单号'); ?>：<?php echo $order_value['order_sn']; ?></h4>
                    </dt>
                    <dd><?php echo $this->translate('订单状态'); ?>：<?php echo $this->frontwebsite()->getOneOrderStateInfo($order_value['order_state']); ?></dd>
                    <dd><?php echo $this->translate('订单总金额'); ?>：<span class="ect-color"><?php echo $order_value['currency_symbol'] . $order_value['order_amount'] . $order_value['currency_unit']; ?></span></dd>
                    <dd><?php echo $this->translate('下单时间'); ?>：<?php echo date("Y-m-d H:i:s",$order_value['order_time']); ?></dd>
                </dl>
                <i class="pull-right fa fa-angle-right"></i> </a>
        </li>
        <?php } ?>
        <div>
            <?php echo ( count($this->order_list) > 0 ) ? $this->paginationControl($this->order_list, 'Sliding', 'mobile/page',array('page_url'=>$this->url('m_order/default/order_page', array('action'=>'index', 'order_state'=>$this->order_state)))) : ""; ?>
        </div>
        <?php } else { ?>
        <li><?php echo '<p>' . $this->translate('暂时无订单！') . '</p>'; ?></li>
        <?php } ?>
    </ul>
</div>