<div class="header_menu">
    <div class="container">
        <div class="header-nav clearfix">
            <?php echo $this->partial('site/headermenu'); ?>
        </div>
    </div>
</div>
</div>

<div class="container">
    <div class="xm-plain-box">
        <div class="box-bd">
            <div class="row">
                <h3><?php echo $this->message; ?></h3>
            </div>
        </div>
    </div>
</div>