    		<div style="height:30px;border-bottom:4px solid #DFDFDF;">
        	<p class="pull-left" style="font-size:16px; line-height:30px;"><strong><?php echo $this->translate('属性分组'); ?></strong></p>
        	<p class="pull-right">
            <a href="<?php echo $this->url('attribute/default',array('action'=>'addAttributeGroup')); ?>" class="btn btn-small btn-primary"><i class="icon-plus icon-white"></i> <?php echo $this->translate('添加属性组'); ?></a>&nbsp;
            <a href="<?php echo $this->myviewalias()->dbshopHelpUrl('goods_attribute_group_set'); ?>" target="_blank" class="btn btn-small btn-info"><i class="icon-info-sign icon-white"></i> <?php echo $this->translate('查看帮助说明'); ?></a>
            </p>
        	</div>
            <form action="<?php echo $this->url('attribute/default',array('action'=>'allAttributeGroupUpdate')); ?>" name="submit_form" id="submit_form" method="post">
            <table class="table table-hover">
            <thead style="background:#CCC;">
            	<tr>
                    <th width="5%">ID</th>
                    <th width="60%"><?php echo $this->translate('属性组名称'); ?></th>
                    <th width="20%"><?php echo $this->translate('属性组排序'); ?></th>
                    <th width="10%"><?php echo $this->translate('操作'); ?></th>
                </tr>
            </thead>
            <?php
			if ($this->attribute_group) {
				foreach ($this->attribute_group as $group_val) {
			?>            
            <tr>
            	<td><?php echo $group_val['attribute_group_id']; ?></td>
            	<td><?php echo $this->escapeHtml($group_val['attribute_group_name']); ?></td>
                <td><input type="text" class="span3" name="attribute_group_sort[<?php echo $group_val['attribute_group_id']; ?>]" value="<?php echo $group_val['attribute_group_sort']; ?>"></td>
            	<td><a href="<?php echo $this->url('attribute/default/attribute-group-id',array('action'=>'editAttributeGroup','attribute_group_id'=>$group_val['attribute_group_id'])); ?>"><?php echo $this->translate('编辑'); ?></a><span>|</span><a href="javascript:;" onclick="return group_del_js(<?php echo $group_val['attribute_group_id']; ?>);"><?php echo $this->translate('删除'); ?></a></td>  
            </tr>
            <?php
				}
			}
			?>
                <tr>
                    <td colspan="4" style="background: #FFF">
                        <div class="pull-left span6" style="height: 30px; line-height: 30px;">
                            <button type="submit" class="btn btn-small btn-primary"><i class="icon-tasks icon-white"></i> <?php echo $this->translate('批量修改'); ?></button>
                        </div>
                    </td>
                </tr>
            </table>
            </form>
            
<script>
//属性组删除js
function group_del_js(group_id) {
	if(window.confirm('<?php echo $this->translate('您确实要删除该属性组吗？'); ?>')) {
	$.post("<?php echo $this->url('attribute/default',array('action'=>'delAttributeGroup')); ?>",{attribute_group_id:group_id},
	function(data){
		if(data != 'false') {
			window.location.href='<?php echo $this->url('attribute/default',array('action'=>'attributeGroup')); ?>';
			return true;
		} else {
			alert('<?php echo $this->translate('属性组删除失败，属性组下存在属性！'); ?>');
		}
	});
	}
	return false;
}
</script>