    		<div id="sticky_navigation" style="height:30px;border-bottom:4px solid #DFDFDF;">
        	<p class="pull-left" style="font-size:16px; line-height:30px;"><strong><?php echo $this->translate('商品属性'); ?></strong></p>
        	<p class="pull-right">
            <a href="<?php echo $this->url('attribute/default',array('action'=>'add')); ?>" class="btn btn-small btn-primary"><i class="icon-plus icon-white"></i> <?php echo $this->translate('添加属性'); ?></a>&nbsp;
            <a href="<?php echo $this->myviewalias()->dbshopHelpUrl('goods_attribute_set'); ?>" target="_blank" class="btn btn-small btn-info"><i class="icon-info-sign icon-white"></i> <?php echo $this->translate('查看帮助说明'); ?></a>
            </p>
        	</div>
            <form action="<?php echo $this->url('attribute/default',array('action'=>'allAttributeUpdate')); ?>" name="submit_form" id="submit_form" method="post">
            <table class="table table-hover">
            <thead style="background:#CCC;">
            	<tr>
                    <th width="5%">ID</th>
                    <th width="20%"><?php echo $this->translate('属性名称'); ?></th>
                    <th width="18%"><?php echo $this->translate('属性分组'); ?></th>
                    <th width="10%"><?php echo $this->translate('属性类型'); ?></th>
                    <th width="10%"><?php echo $this->translate('属性排序'); ?></th>
                    <th width="10%"><?php echo $this->translate('操作'); ?></th>
                </tr>
            </thead>
            <?php
			if ($this->list_attribute) {
				foreach ($this->list_attribute as $attr_val) {
			?>            
            <tr>
            	<td><?php echo $attr_val['attribute_id']; ?></td>
            	<td><?php echo $this->escapeHtml($attr_val['attribute_name']); ?></td>
                <td><?php echo $this->escapeHtml($attr_val['attribute_group_name']); ?></td>
                <td><?php echo ($this->input_array[$attr_val['attribute_type']]); ?></td>
                <td><input type="text" class="span5" name="attribute_sort[<?php echo $attr_val['attribute_id']; ?>]" value="<?php echo $attr_val['attribute_sort']; ?>"></td>
            	<td><a href="<?php echo $this->url('attribute/default/attribute-id',array('action'=>'edit','attribute_id'=>$attr_val['attribute_id'])); ?>"><?php echo $this->translate('编辑'); ?></a><?php if(!in_array($attr_val['attribute_type'], array('input', 'textarea'))) { ?><span>|</span><a href="<?php echo $this->url('attribute/default/attribute-id',array('action'=>'attributeValue','attribute_id'=>$attr_val['attribute_id'])); ?>"><?php echo $this->translate('属性值设置'); ?></a><?php } ?><span>|</span><a href="javascript:;" onclick="return attribute_del_js(<?php echo $attr_val['attribute_id']; ?>);"><?php echo $this->translate('删除'); ?></a></td>  
            </tr>
            <?php
				}
			}
			?>
                <tr>
                    <td colspan="6" style="background: #FFF">
                        <div class="pull-left span6" style="height: 30px; line-height: 30px;">
                            <button type="submit" class="btn btn-small btn-primary"><i class="icon-tasks icon-white"></i> <?php echo $this->translate('批量修改'); ?></button>
                        </div>
                    </td>
                </tr>
            </table>
            </form>
            
<script>
//属性删除js
function attribute_del_js(attribute_id) {
	if(window.confirm('<?php echo $this->translate('您确实要删除该属性吗？'); ?>')) {
	$.post("<?php echo $this->url('attribute/default',array('action'=>'del')); ?>",{attribute_id:attribute_id},
	function(data){
		if(data != 'false') {
			window.location.href='<?php echo $this->url('attribute/default'); ?>';
			return true;
		} else {
			alert('<?php echo $this->translate('属性删除失败！'); ?>');
		}
	});
	}
	return false;
}
</script>