<?php
/**
 * DBShop 电子商务系统
 *
 * ==========================================================================
 * @link      http://www.dbshop.net/
 * @copyright Copyright (c) 2012-2015 DBShop.net Inc. (http://www.dbshop.net)
 * @license   http://www.dbshop.net/license.html License
 * ==========================================================================
 *
 * @author    静静的风
 *
 */

return array(
  'Goods\Module'                               => __DIR__ . '/Module.php',
  'Goods\Controller\AskController'             => __DIR__ . '/src/Goods/Controller/AskController.php',
  'Goods\Controller\AttributeController'       => __DIR__ . '/src/Goods/Controller/AttributeController.php',
  'Goods\Controller\BrandController'           => __DIR__ . '/src/Goods/Controller/BrandController.php',
  'Goods\Controller\ClassController'           => __DIR__ . '/src/Goods/Controller/ClassController.php',
  'Goods\Controller\CommentController'         => __DIR__ . '/src/Goods/Controller/CommentController.php',
  'Goods\Controller\GoodsController'           => __DIR__ . '/src/Goods/Controller/GoodsController.php',
  'Goods\Controller\PromotionsController'      => __DIR__ . '/src/Goods/Controller/PromotionsController.php',
  'Goods\Controller\CouponController'          => __DIR__ . '/src/Goods/Controller/CouponController.php',
  'Goods\Controller\TagController'             => __DIR__ . '/src/Goods/Controller/TagController.php',
  'Goods\Model\Goods'                          => __DIR__ . '/src/Goods/Model/Goods.php',
  'Goods\Model\GoodsAsk'                       => __DIR__ . '/src/Goods/Model/GoodsAsk.php',
  'Goods\Model\GoodsAskBase'                   => __DIR__ . '/src/Goods/Model/GoodsAskBase.php',
  'Goods\Model\GoodsAskBaseTable'              => __DIR__ . '/src/Goods/Model/GoodsAskBaseTable.php',
  'Goods\Model\GoodsAskTable'                  => __DIR__ . '/src/Goods/Model/GoodsAskTable.php',
  'Goods\Model\GoodsAttribute'                 => __DIR__ . '/src/Goods/Model/GoodsAttribute.php',
  'Goods\Model\GoodsAttributeExtend'           => __DIR__ . '/src/Goods/Model/GoodsAttributeExtend.php',
  'Goods\Model\GoodsAttributeExtendTable'      => __DIR__ . '/src/Goods/Model/GoodsAttributeExtendTable.php',
  'Goods\Model\GoodsAttributeGroup'            => __DIR__ . '/src/Goods/Model/GoodsAttributeGroup.php',
  'Goods\Model\GoodsAttributeGroupExtend'      => __DIR__ . '/src/Goods/Model/GoodsAttributeGroupExtend.php',
  'Goods\Model\GoodsAttributeGroupExtendTable' => __DIR__ . '/src/Goods/Model/GoodsAttributeGroupExtendTable.php',
  'Goods\Model\GoodsAttributeGroupTable'       => __DIR__ . '/src/Goods/Model/GoodsAttributeGroupTable.php',
  'Goods\Model\GoodsAttributeTable'            => __DIR__ . '/src/Goods/Model/GoodsAttributeTable.php',
  'Goods\Model\GoodsAttributeValue'            => __DIR__ . '/src/Goods/Model/GoodsAttributeValue.php',
  'Goods\Model\GoodsAttributeValueExtend'      => __DIR__ . '/src/Goods/Model/GoodsAttributeValueExtend.php',
  'Goods\Model\GoodsAttributeValueExtendTable' => __DIR__ . '/src/Goods/Model/GoodsAttributeValueExtendTable.php',
  'Goods\Model\GoodsAttributeValueTable'       => __DIR__ . '/src/Goods/Model/GoodsAttributeValueTable.php',
  'Goods\Model\GoodsBrand'                     => __DIR__ . '/src/Goods/Model/GoodsBrand.php',
  'Goods\Model\GoodsBrandExtend'               => __DIR__ . '/src/Goods/Model/GoodsBrandExtend.php',
  'Goods\Model\GoodsBrandExtendTable'          => __DIR__ . '/src/Goods/Model/GoodsBrandExtendTable.php',
  'Goods\Model\GoodsBrandTable'                => __DIR__ . '/src/Goods/Model/GoodsBrandTable.php',
  'Goods\Model\GoodsClass'                     => __DIR__ . '/src/Goods/Model/GoodsClass.php',
  'Goods\Model\GoodsClassShow'                 => __DIR__ . '/src/Goods/Model/GoodsClassShow.php',
  'Goods\Model\GoodsClassShowTable'            => __DIR__ . '/src/Goods/Model/GoodsClassShowTable.php',
  'Goods\Model\GoodsClassTable'                => __DIR__ . '/src/Goods/Model/GoodsClassTable.php',
  'Goods\Model\GoodsCombination'               => __DIR__ . '/src/Goods/Model/GoodsCombination.php',
  'Goods\Model\GoodsCombinationTable'          => __DIR__ . '/src/Goods/Model/GoodsCombinationTable.php',
  'Goods\Model\GoodsComment'                   => __DIR__ . '/src/Goods/Model/GoodsComment.php',
  'Goods\Model\GoodsCommentBase'               => __DIR__ . '/src/Goods/Model/GoodsCommentBase.php',
  'Goods\Model\GoodsCommentBaseTable'          => __DIR__ . '/src/Goods/Model/GoodsCommentBaseTable.php',
  'Goods\Model\GoodsCommentTable'              => __DIR__ . '/src/Goods/Model/GoodsCommentTable.php',
  'Goods\Model\GoodsCustom'                    => __DIR__ . '/src/Goods/Model/GoodsCustom.php',
  'Goods\Model\GoodsCustomTable'               => __DIR__ . '/src/Goods/Model/GoodsCustomTable.php',
  'Goods\Model\GoodsExtend'                    => __DIR__ . '/src/Goods/Model/GoodsExtend.php',
  'Goods\Model\GoodsExtendTable'               => __DIR__ . '/src/Goods/Model/GoodsExtendTable.php',
  'Goods\Model\GoodsImage'                     => __DIR__ . '/src/Goods/Model/GoodsImage.php',
  'Goods\Model\GoodsImageTable'                => __DIR__ . '/src/Goods/Model/GoodsImageTable.php',
  'Goods\Model\GoodsInAttribute'               => __DIR__ . '/src/Goods/Model/GoodsInAttribute.php',
  'Goods\Model\GoodsInAttributeTable'          => __DIR__ . '/src/Goods/Model/GoodsInAttributeTable.php',
  'Goods\Model\GoodsInClass'                   => __DIR__ . '/src/Goods/Model/GoodsInClass.php',
  'Goods\Model\GoodsInClassTable'              => __DIR__ . '/src/Goods/Model/GoodsInClassTable.php',
  'Goods\Model\GoodsPriceExtend'               => __DIR__ . '/src/Goods/Model/GoodsPriceExtend.php',
  'Goods\Model\GoodsPriceExtendColor'          => __DIR__ . '/src/Goods/Model/GoodsPriceExtendColor.php',
  'Goods\Model\GoodsPriceExtendColorTable'     => __DIR__ . '/src/Goods/Model/GoodsPriceExtendColorTable.php',
  'Goods\Model\GoodsPriceExtendGoods'          => __DIR__ . '/src/Goods/Model/GoodsPriceExtendGoods.php',
  'Goods\Model\GoodsPriceExtendGoodsTable'     => __DIR__ . '/src/Goods/Model/GoodsPriceExtendGoodsTable.php',
  'Goods\Model\GoodsPriceExtendSize'           => __DIR__ . '/src/Goods/Model/GoodsPriceExtendSize.php',
  'Goods\Model\GoodsPriceExtendSizeTable'      => __DIR__ . '/src/Goods/Model/GoodsPriceExtendSizeTable.php',
  'Goods\Model\GoodsPriceExtendTable'          => __DIR__ . '/src/Goods/Model/GoodsPriceExtendTable.php',
  'Goods\Model\GoodsRelated'                   => __DIR__ . '/src/Goods/Model/GoodsRelated.php',
  'Goods\Model\GoodsRelatedTable'              => __DIR__ . '/src/Goods/Model/GoodsRelatedTable.php',
  'Goods\Model\GoodsTable'                     => __DIR__ . '/src/Goods/Model/GoodsTable.php',
  'Goods\Model\GoodsTag'                       => __DIR__ . '/src/Goods/Model/GoodsTag.php',
  'Goods\Model\GoodsTagExtend'                 => __DIR__ . '/src/Goods/Model/GoodsTagExtend.php',
  'Goods\Model\GoodsTagExtendTable'            => __DIR__ . '/src/Goods/Model/GoodsTagExtendTable.php',
  'Goods\Model\GoodsTagGroup'                  => __DIR__ . '/src/Goods/Model/GoodsTagGroup.php',
  'Goods\Model\GoodsTagGroupExtend'            => __DIR__ . '/src/Goods/Model/GoodsTagGroupExtend.php',
  'Goods\Model\GoodsTagGroupExtendTable'       => __DIR__ . '/src/Goods/Model/GoodsTagGroupExtendTable.php',
  'Goods\Model\GoodsTagGroupTable'             => __DIR__ . '/src/Goods/Model/GoodsTagGroupTable.php',
  'Goods\Model\GoodsTagInGoods'                => __DIR__ . '/src/Goods/Model/GoodsTagInGoods.php',
  'Goods\Model\GoodsTagInGoodsTable'           => __DIR__ . '/src/Goods/Model/GoodsTagInGoodsTable.php',
  'Goods\Model\GoodsTagTable'                  => __DIR__ . '/src/Goods/Model/GoodsTagTable.php',
  'Goods\Model\PromotionsRule'                 => __DIR__ . '/src/Goods/Model/PromotionsRule.php',
  'Goods\Model\PromotionsRuleTable'            => __DIR__ . '/src/Goods/Model/PromotionsRuleTable.php',
  'Goods\Model\VirtualGoods'                   => __DIR__ . '/src/Goods/Model/VirtualGoods.php',
  'Goods\Model\VirtualGoodsTable'              => __DIR__ . '/src/Goods/Model/VirtualGoodsTable.php',
  'Goods\Model\GoodsIndex'                     => __DIR__ . '/src/Goods/Model/GoodsIndex.php',
  'Goods\Model\GoodsIndexTable'                => __DIR__ . '/src/Goods/Model/GoodsIndexTable.php',
  'Goods\Model\GoodsRelation'                  => __DIR__ . '/src/Goods/Model/GoodsRelation.php',
  'Goods\Model\GoodsRelationTable'             => __DIR__ . '/src/Goods/Model/GoodsRelationTable.php',
  'Goods\Model\GoodsUsergroupPrice'            => __DIR__ . '/src/Goods/Model/GoodsUsergroupPrice.php',
  'Goods\Model\GoodsUsergroupPriceTable'       => __DIR__ . '/src/Goods/Model/GoodsUsergroupPriceTable.php',
  'Goods\Model\Coupon'                         => __DIR__ . '/src/Goods/Model/Coupon.php',
  'Goods\Model\CouponTable'                    => __DIR__ . '/src/Goods/Model/CouponTable.php',
  'Goods\Model\GoodsAdvSpecGroup'              => __DIR__ . '/src/Goods/Model/GoodsAdvSpecGroup.php',
  'Goods\Model\GoodsAdvSpecGroupTable'         => __DIR__ . '/src/Goods/Model/GoodsAdvSpecGroupTable.php',

  'Goods\Service\CouponRuleService'            => __DIR__ . '/src/Goods/Service/CouponRuleService.php',
  'Goods\Service\PromotionsRuleService'        => __DIR__ . '/src/Goods/Service/PromotionsRuleService.php',
);
