            <table class="table table-hover">
            	<thead style="background:#CCC;">
                	<tr>
                    	<th width="80%"><?php echo $this->translate('商品信息'); ?></th>
                    </tr>
                </thead>
                <?php if ($this->favorites_list->getTotalItemCount() > 0) { foreach ($this->favorites_list as $favorites_value) { ?>
               	<tr>
                	<td><a href="<?php echo $this->url('frontgoods/default', array('goods_id'=>$favorites_value['goods_id'], 'class_id'=>$favorites_value['class_id'])); ?>" target="_blank"><img src="<?php echo $this->basePath($this->frontwebsite()->shopadminGoodsImage($favorites_value['goods_thumbnail_image'])); ?>"  style=" height:65px;width:65px;border:1px solid #D7D7D7"></a>&nbsp;&nbsp;<a href="<?php echo $this->url('frontgoods/default', array('goods_id'=>$favorites_value['goods_id'], 'class_id'=>$favorites_value['class_id'])); ?>" target="_blank"><?php echo $this->escapeHtml($favorites_value['goods_name']); ?></a></td>
                </tr>
                <?php } } else { ?>
                <tr>
                	<td colspan="2"><?php echo $this->translate('暂无商品收藏！'); ?></td>
                </tr>
                <?php } ?>
                    <tr>
                    <td colspan="2">
        		<?php echo ( count($this->favorites_list) > 0 ) ? $this->paginationControl($this->favorites_list, 'Sliding', 'common/ajax-pages',array('page_url'=>$this->url('user/default/user_id/other-page',array('action'=>'ajaxfavorites','user_id'=>$this->user_id)),'show_div_id'=>$this->show_div_id)) : ""; ?>
                    </td>
                    </tr>
    		</table>