<table class="table table-hover">
            <thead style="background:#CCC;">
            	<tr>
                    <th width="18%"><?php echo $this->translate('邮件标题'); ?></th>
                    <th width="50%"><?php echo $this->translate('邮件内容'); ?></th>
                    <th width="15%"><?php echo $this->translate('发送时间'); ?></th>
                    <th width="10%"><?php echo $this->translate('发送状态'); ?></th>
                    <th width="6%"><?php echo $this->translate('操作'); ?></th>
                </tr>
            </thead>
            <?php if(count($this->user_mail_log_list) == 0) { ?>
            <tr>
            	<td colspan="7"><?php echo $this->translate('还没有发送过邮件'); ?></td>  
            </tr>
            <?php } else {
            foreach($this->user_mail_log_list as $value) { ?>
            <tr>
            	<td><?php echo $this->escapeHtml($value['mail_subject']); ?></td>
            	<td><?php echo $value['mail_body']; ?></td>
            	<td><?php echo date('Y-m-d H:i:s',$value['send_time']); ?></td>
            	<td><?php if ($value['send_state'] == 1) echo $this->translate('成功'); else echo $this->translate('失败'); ?></td>
            	<td>
                <a href="javascript:;" onClick="return del_mail_log_js(<?php echo $value['mail_log_id']; ?>);"><?php echo $this->translate('删除'); ?></a>
                </td>  
            </tr>
            <?php } } ?>
            <tr>
            	<td colspan="5" style="background:#FFF">
            	<div class="pull-left" style="height:30px; line-height:30px;">

            	</div>
            	<?php echo ( count($this->user_mail_log_list) > 0 ) ? $this->paginationControl($this->user_mail_log_list,'Sliding','common/ajax-pages',array('page_url'=>$this->url('user/default/mail-log-page',array('action'=>'maillog','controller'=>'user','user_id'=>$this->user_id)),'show_div_id'=>$this->show_div_id)) : ''; ?> 
            	</td> 
            </tr>
            </table>