    		<div id="sticky_navigation" style="height:30px;border-bottom:4px solid #DFDFDF;">
        	<p class="pull-left" style="font-size:16px; line-height:30px;"><strong><?php echo $this->translate('客户扩展信息'); ?></strong></p>
        	<p class="pull-right">
            <a href="<?php echo $this->url('user/default',array('action'=>'addUserRegExtend')); ?>" class="btn btn-small btn-primary"><i class="icon-plus icon-white"></i> <?php echo $this->translate('添加扩展信息'); ?></a>&nbsp;
			<a href="<?php echo $this->myviewalias()->dbshopHelpUrl('user_reg_ext_set'); ?>" target="_blank" class="btn btn-small btn-info"><i class="icon-info-sign icon-white"></i> <?php echo $this->translate('查看帮助说明'); ?></a>
			</p>
        	</div>
            <table class="table table-hover">
            <thead style="background:#CCC;">
            	<tr>
                    <th width="10%"><?php echo $this->translate('字段名称'); ?></th>
                    <th width="15%"><?php echo $this->translate('字段标题'); ?></th>
                    <th width="10%"><?php echo $this->translate('字段类型'); ?></th>
                    <th width="8%"><?php echo $this->translate('排序'); ?></th>
                    <th width="8%"><?php echo $this->translate('状态'); ?></th>
                    <th width="8%"><?php echo $this->translate('是否为空'); ?></th>
                    <th width="10%"><?php echo $this->translate('操作'); ?></th>
                </tr>
            </thead>
            <?php
			if ($this->field_array) {
				foreach ($this->field_array as $field_val) {
			?>            
            <tr>
            	<td><?php echo $this->escapeHtml($field_val['field_name']); ?></td>
				<td><?php echo $this->escapeHtml($field_val['field_title']); ?></td>
				<td><?php
					$field_type_array = array(
						'radio'		=> $this->translate('单选表单'),
						'checkbox'	=> $this->translate('多选表单'),
						'select'	=> $this->translate('下拉表单'),
						'upload'	=> $this->translate('上传附件表单'),
						'text'		=> $this->translate('单行文本表单'),
						'textarea'	=> $this->translate('多行文本表单'),
					);
					echo $field_type_array[$field_val['field_type']];
					?>
				</td>
				<td><?php echo $field_val['field_sort']; ?></td>
            	<td><?php echo ($field_val['field_state'] == 1 ? $this->translate('启用') : $this->translate('关闭')); ?></td>
            	<td><?php echo ($field_val['field_null'] == 1 ? $this->translate('是') : $this->translate('否')); ?></td>
            	<td>
					<a href="<?php echo $this->url('user/default/reg-extend',array('action'=>'editUserRegExtend', 'field_id'=>$field_val['field_id'])); ?>"><?php echo $this->translate('编辑'); ?></a>
					<span>|</span>
					<a href="javascript:;" onclick="return field_del_js(<?php echo $field_val['field_id']; ?>);"><?php echo $this->translate('删除'); ?></a>
				</td>
            </tr>
            <?php
				}
			}
			?>
            </table>
            
<script>
	//客户扩展删除js
	function field_del_js(field_id) {
		if(window.confirm('<?php echo $this->translate('您确实要删除该客户扩展信息吗？'); ?>')) {
			$.post("<?php echo $this->url('user/default',array('action'=>'delUserRegExtend')); ?>",{field_id:field_id},
					function(data){
						if(data != 'false') {
							window.location.href='<?php echo $this->url('user/default',array('action'=>'userRegExtend')); ?>';
							return true;
						} else {
							alert('<?php echo $this->translate('扩展删除失败！'); ?>');
						}
					});
		}
		return false;
	}
</script>