    		<div id="sticky_navigation" style="height:30px;border-bottom:4px solid #DFDFDF;">
        	<p class="pull-left" style="font-size:16px; line-height:30px;"><strong><?php echo $this->translate('在线客服管理'); ?></strong></p>
        	<p class="pull-right">
            <a href="<?php echo $this->url('online/default',array('action'=>'add')); ?>" class="btn btn-small btn-primary"><i class="icon-plus icon-white"></i> <?php echo $this->translate('添加在线客服'); ?></a>&nbsp;
            <a href="<?php echo $this->myviewalias()->dbshopHelpUrl('online_set'); ?>" target="_blank" class="btn btn-small btn-info"><i class="icon-info-sign icon-white"></i> <?php echo $this->translate('查看帮助说明'); ?></a>
            </p>
        	</div>
            <table class="table table-hover">
            <thead style="background:#CCC;">
            	<tr>
                    <th width="5%">ID</th>
                    <th width="20%"><?php echo $this->translate('客服名称'); ?></th>
                    <th width="12%"><?php echo $this->translate('客服组名称'); ?></th>
                    <th width="8%"><?php echo $this->translate('通讯工具'); ?></th>
                    <th width="5%"><?php echo $this->translate('排序'); ?></th>
                    <th width="5%"><?php echo $this->translate('状态'); ?></th>
                    <th width="8%"><?php echo $this->translate('操作'); ?></th>
                </tr>
            </thead>
            <?php if($this->online_list) foreach ($this->online_list as $online_value) { ?>            
            <tr>
            	<td><?php echo $online_value['online_id']; ?></td>
            	<td><?php echo $this->escapeHtml($online_value['online_name']); ?></td>
                <td><?php echo $this->escapeHtml($online_value['group_name']); ?></td>
                <td><?php echo $online_value['online_web_code']; ?></td>
                <td><?php echo $online_value['online_sort']; ?></td>
                <td><?php echo ($online_value['online_state'] == 1 ? $this->translate('启用') : $this->translate('禁用')); ?></td>
            	<td><a href="<?php echo $this->url('online/default/online_id',array('action'=>'edit','online_id'=>$online_value['online_id'])); ?>"><?php echo $this->translate('编辑'); ?></a><span>|</span><a href="javascript:;" onclick="return online_del_js(<?php echo $online_value['online_id']; ?>);"><?php echo $this->translate('删除'); ?></a></td>  
            </tr>
            <?php
				}
			?>
            </table>
            
<script>
//客服删除js
function online_del_js(online_id) {
	if(window.confirm('<?php echo $this->translate('您确实要删除该在线客服吗？'); ?>')) {
	$.post("<?php echo $this->url('online/default',array('action'=>'del')); ?>",{online_id:online_id},
	function(data){
		if(data != 'false') {
			window.location.href='<?php echo $this->url('online/default'); ?>';
			return true;
		} else {
			alert('<?php echo $this->translate('在线客服删除失败！'); ?>');
		}
	});
	}
	return false;
}
</script>