<div class="tabbable tabs-left">
    <ul class="nav nav-tabs">
        <li><h5><?php echo $this->translate('在线客服样式'); ?></h5></li>
        <li class="active"><a data-toggle="tab" href="#express_a"><?php echo $this->translate('基本信息'); ?></a></li>
    </ul>
    <form class="form-horizontal" name="online_style_form" id="online_style_form" method="post" action="">
        <div class="tab-content">
            <div id="sticky_navigation" style="height:30px;border-bottom:4px solid #DFDFDF;">
                <div class="pull-left" style="font-size:16px;line-height:30px;"><strong><?php echo $this->translate('在线客服样式设置'); ?></strong></div>
                <div class="pull-right">
                    <a href="<?php echo $this->serverUrl(true); ?>" class="btn btn-small btn-warning"><i class="icon-repeat icon-white"></i> <?php echo $this->translate('刷新'); ?></a>&nbsp;
                    <button type="submit" class="btn btn-small btn-primary"><i class="icon-ok icon-white"></i> <?php echo $this->translate('保存设置信息'); ?></button>&nbsp;
                    <a href="<?php echo $this->myviewalias()->dbshopHelpUrl('online_style_set'); ?>" target="_blank" class="btn btn-small btn-info"><i class="icon-info-sign icon-white"></i> <?php echo $this->translate('查看帮助说明'); ?></a>
                </div>
            </div>
            <div id="express_a" class="tab-pane active">
                <div class="well admin_add_header_well"><?php echo $this->translate('基本信息'); ?></div>
                <div class="well admin_add_well">
                    <div class="control-group">
                        <label for="input01" class="control-label"><?php echo $this->translate('客服样式选择'); ?>：</label>
                        <div class="controls">
                            <select name="online_style" class="span3">
                                <option value="default" <?php if(isset($this->online_type_array['online']) and $this->online_type_array['online']['style'] == 'default') echo 'selected'; ?>><?php echo $this->translate('默认样式'); ?></option>
                                <option value="default_1" <?php if(isset($this->online_type_array['online']) and $this->online_type_array['online']['style'] == 'default_1') echo 'selected'; ?>><?php echo $this->translate('个性样式-1'); ?></option>
                                <!--<option value="default_2" <?php if(isset($this->online_type_array['online']) and $this->online_type_array['online']['style'] == 'default_2') echo 'selected'; ?>><?php echo $this->translate('个性样式-2'); ?></option>-->
                            </select>
                            <!-- <a href="" target="_blank" class="btn btn-primary btn-small"><?php echo $this->translate('点击链接查看客服的不同样式'); ?></a>-->
                        </div>
                    </div>

                </div>
            </div>


        </div>
    </form>
</div>