<div class="row-fluid" id="goods_list">
    <div class="row span10 offset1" style="margin-bottom:15px;">
    <h3 class="title text-center"><?php echo $this->escapeHtml($this->single_article_info->single_article_title . $this->single_article_info->single_article_title_extend); ?></h3>
	<hr style="margin-top:10px;" />
    	<div style="font-size:16px;" class="edit_table_css">
        <?php echo $this->single_article_info->single_article_body; ?>
        </div>
        <?php
        $goods_share_info = $this->frontwebsite()->getDbshopGoodsShare();
        if(!empty($goods_share_info['share_type'])) {
            echo "<script>var dbshop_baidushare_path='". $this->basePath('/public/js/baiduShare/')."';</script>";
        ?>
        <hr style="margin-bottom: 3px;">
        <div class="pull-right">
            <?php echo $goods_share_info['share_code']; ?>
        </div>
        <?php } ?>
    </div>
    
     
</div>