<div class="tabbable tabs-left">
              <ul class="nav nav-tabs">
              	<li><h5><?php echo $this->translate('标签信息'); ?></h5></li>
                <li class="active"><a data-toggle="tab" href="#tag_a"><?php echo $this->translate('基本信息'); ?></a></li>
                <?php if($this->tag_info) { ?>
                <li><a data-toggle="tab" href="#tag_b"><?php echo $this->translate('标签商品'); ?></a></li>
                <?php } ?>
              </ul>
              <form class="form-horizontal" name="tag_form" id="tag_form" method="post" action="">
              <input type="hidden" name="tag_id" id="tag_id" value="<?php if($this->tag_info) echo $this->tag_info->tag_id; else echo ''; ?>" />
              <div class="tab-content">
    			<div id="sticky_navigation" style="height:30px;border-bottom:4px solid #DFDFDF;">
        			<div class="pull-left" style="font-size:16px;line-height:30px;"><strong><?php if($this->tag_info) echo $this->translate('编辑'); else echo $this->translate('新加'); ?><?php echo $this->translate('普通商品标签'); ?></strong></div>
        			<div class="pull-right">
                	<a href="<?php echo $this->url('tag/default',array('action'=>'index')); ?>" class="btn btn-small"><i class="icon-arrow-left"></i> <?php echo $this->translate('返回标签列表'); ?></a>&nbsp;
                	<a href="<?php echo $this->serverUrl(true); ?>" class="btn btn-small btn-warning"><i class="icon-repeat icon-white"></i> <?php echo $this->translate('刷新'); ?></a>&nbsp;
                    <?php if($this->tag_info) { ?>
                    <a href="javascript:;" onclick="return tag_del_js(<?php echo $this->tag_info->tag_id ?>);" class="btn btn-small btn-danger"><i class="icon-remove icon-white"></i> <?php echo $this->translate('删除标签'); ?></a>&nbsp;
                    <?php } ?>
                	<button type="submit" class="btn btn-small btn-primary"><i class="icon-ok icon-white"></i> <?php echo $this->translate('保存标签信息'); ?></button>&nbsp;
                	<a href="<?php echo $this->myviewalias()->dbshopHelpUrl('goods_tag_set'); ?>" target="_blank" class="btn btn-small btn-info"><i class="icon-info-sign icon-white"></i> <?php echo $this->translate('查看帮助说明'); ?></a>
                	</div>
        		</div>
                <div id="tag_a" class="tab-pane active">
                	<div class="well admin_add_header_well"><?php echo $this->translate('基本信息'); ?></div>
                	<div class="well admin_add_well">
                    	<div class="control-group">
                  			<label for="input01" class="control-label"><?php echo $this->translate('标签分组'); ?><span class="must_add_value">*</span>：</label>
           					<div class="controls">
              					<select id="tag_group_id" name="tag_group_id" class="span2">
                                	<option value=""><?php echo $this->translate('请选择标签组'); ?></option>
                                    <?php if ($this->tag_group) foreach($this->tag_group as $group_value) { ?>
                                    <option <?php echo ($this->tag_info and $this->tag_info->tag_group_id == $group_value['tag_group_id']) ? 'selected="selected"' : ''; ?> value="<?php echo $group_value['tag_group_id']; ?>"><?php echo $this->escapeHtml($group_value['tag_group_name']).(!empty($group_value['tag_group_mark']) ? ' == ['.$group_value['tag_group_mark'].']' : ''); ?></option>
                                    <?php } ?>
                                </select>
            				</div>                        
                        </div>   
                    	<div class="control-group">
                  			<label for="input01" class="control-label"><?php echo $this->translate('标签名称'); ?><span class="must_add_value">*</span>：</label>
           					<div class="controls">
                                <?php if($this->tag_info) { ?>
                                    <input type="text" id="tag_name"  name="tag_name" class="span6" value="<?php echo ($this->tag_info ? $this->escapeHtml($this->tag_info->tag_name) : ''); ?>">
                                <?php } else { ?>
                                    <textarea name="tag_name" id="tag_name" class="span4" rows="5" placeholder="<?php echo $this->translate('一次性可以添加多个标签，一行一个，用回车分行即可。'); ?>"></textarea>
                                <?php } ?>
            				</div>
                        </div>
                        <div class="control-group">
                            <label for="input01" class="control-label"><?php echo $this->translate('标签排序'); ?><span class="must_add_value">*</span>：</label>
                            <div class="controls">
                                <input type="text" id="tag_sort"  name="tag_sort" class="span2" value="<?php if($this->tag_info and $this->tag_info->tag_sort) echo $this->tag_info->tag_sort; else echo '255'; ?>">
                            </div>
                        </div>
                        <div class="control-group">
                            <label for="input01" class="control-label"><?php echo $this->translate('颜色块设置'); ?>：</label>
                            <div class="controls">
                                <input type="text" name="tag_str" id="tag_str" value="<?php echo ($this->tag_info ? $this->tag_info->tag_str : ''); ?>" readonly="readonly" class="span1 iColorPicker">
                                <?php if(isset($this->tag_info->tag_str) and !empty($this->tag_info->tag_str)) { ?>
                                    <button type="button" class="btn btn-small" onclick="$('#tag_str').val('');"><?php echo $this->translate('点击取消'); ?></button>
                                <?php } ?>
                                <b><?php echo $this->translate('当开启高级商品规格，且标签组为颜色时，这里需要选择颜色。用于商品编辑内的规格颜色显示。'); ?></b>
                            </div>
                        </div>
                  	</div>
                </div>
				<div id="tag_b" class="tab-pane">
                	<div class="well admin_add_header_well"><?php echo $this->translate('标签商品'); ?></div>
                	<div class="well admin_add_well">
                        <div class="message_one">
                    	</div>
                        <?php if($this->tag_info) { ?>
                        <div class="control-group">
                            <input type="text" placeholder="<?php echo $this->translate('请输入需要添加的商品部分或者全部名称'); ?>" id="tag_goods_keyword" name="tag_goods_keyword"  value="" class="span5"><input type="hidden" name="tag_goods_id" id="tag_goods_id" value="" />&nbsp;&nbsp;<button type="button" onclick="add_tag_goods_js();" class="btn btn-small btn-primary"><i class="icon-plus icon-white"></i> <?php echo $this->translate('点击添加标签商品'); ?></button>
                            <i class="cus-help shop_admin_help_note" data-content="<?php echo $this->translate('在输入框中输入商品部分或者全部名称，然后点击添加按钮，即可添加标签商品'); ?>"></i>
                        </div>
                        <?php } ?>
                        <table class="table table-hover" id="list_goods_show">

            			</table>                  
                                                                                                                       
                  	</div>
                </div>
                
             </div>
              </form>
</div>
<script>var imageUrl='<?php echo $this->basePath('/public/js/iColorPicker/color.png'); ?>';</script>
<script src="<?php echo $this->basePath('/public/js/iColorPicker/iColorPicker.js'); ?>"></script>
<link href="<?php echo $this->basePath('public/js/jquery-autocomplete/jquery.autocomplete.css'); ?>" rel="stylesheet">
<script src="<?php echo $this->basePath('public/js/jquery-autocomplete/jquery.autocomplete.min.js'); ?>"></script>
<script>
$(document).ready(function() {
	$("#tag_form").validate({
		rules: {
            tag_group_id: {
                required: true
            },
			tag_name: {
				required: true,
				maxlength:60
			},
            tag_sort: {
                required: true,
                min:1
            }
		},
		messages: {
            tag_group_id: {
                required: "<?php echo $this->translate('请选择标签分组！'); ?>"
            },
			tag_name: {
				required: "<?php echo $this->translate('请输入标签名称！'); ?>",
				maxlength:"<?php echo $this->translate('标签名称最长为60个汉字！'); ?>"
			},
            tag_sort: {
                required: "<?php echo $this->translate('标签排序不能为空！'); ?>",
                min: "<?php echo $this->translate('标签排序最小为1！'); ?>"
            }
		}
	});
});

//标签删除js
function tag_del_js(tag_id) {
	if(window.confirm('<?php echo $this->translate('您确实要删除该标签吗？'); ?>')) {
	$.post("<?php echo $this->url('tag/default',array('action'=>'del')); ?>",{tag_id:tag_id},
	function(data){
		if(data != 'false') {
			window.location.href='<?php echo $this->url('tag/default',array('action'=>'index')); ?>';
			return true;
		} else {
			alert('<?php echo $this->translate('标签删除失败！'); ?>');
		}
	});
	}
	return false;
}

<?php if($this->tag_info) { ?>
//ajax获取分类下面的商品
dbshop_ajax_list('<?php echo $this->url('tag/default',array('action'=>'ajaxgoods','tag_id'=>$this->tag_info->tag_id)); ?>', 'list_goods_show');
//单次删除标签中的商品
function del_tag_goods_js(goods_id) {
    if(window.confirm('<?php echo $this->translate('您确实要将此商品从该标签中删除吗？'); ?>')) {
        $.post("<?php echo $this->url('tag/default',array('action'=>'delOneTagGoods')); ?>",{goods_id:goods_id,tag_id:<?php echo $this->tag_info->tag_id; ?>},
            function(data){
                if(data != 'false') {
                    //ajax获取标签下面的商品
                    dbshop_ajax_list('<?php echo $this->url('tag/default',array('action'=>'ajaxgoods','tag_id'=>$this->tag_info->tag_id)); ?>', 'list_goods_show');
                } else {
                    alert('<?php echo $this->translate('删除失败！'); ?>');
                }
            });
    }
}
//jquery-autocomplete查询商品
$("#tag_goods_keyword").autocomplete("<?php echo $this->url('goods/default',array('action'=>'autocompleteGoodsSearch')); ?>", {
    //mustMatch: true,
    max: 20,
    minChars:1,
    scrollHeight:400
});
$("#tag_goods_keyword").result(function(event, data, formatted) {
    if (data) $("#tag_goods_id").val(data[1]);
});
//添加标签商品
function add_tag_goods_js() {
    var tag_id 	     = $('#tag_id').val();
    var tag_goods_id = $('#tag_goods_id').val();
    if(tag_goods_id == '') {
        alert('<?php echo $this->translate('该商品不存在，请从新选择！'); ?>');
        return false;
    }
    $.post("<?php echo $this->url('tag/default',array('action'=>'addTagGoods', 'controller'=>'tag')); ?>",{tag_id:tag_id,tag_goods_id:tag_goods_id},
        function(data){
            if(data.state == 'true') {
                $('#tag_goods_keyword').val('');
                $('#tag_goods_id').val('');
                dbshop_ajax_list('<?php echo $this->url('tag/default',array('action'=>'ajaxgoods','tag_id'=>$this->tag_info->tag_id)); ?>', 'list_goods_show');
            } else if(data.state == 'have') {
                alert('<?php echo $this->translate('该标签商品已经存在，无需再次添加！'); ?>');
            } else {
                alert('<?php echo $this->translate('标签商品添加失败！'); ?>');
            }
        },'json');
}

<?php } ?>
</script>