    		<div id="sticky_navigation" style="height:30px;border-bottom:4px solid #DFDFDF;">
        	<p class="pull-left" style="font-size:16px; line-height:30px;"><strong><?php echo $this->translate('普通商品标签'); ?></strong> (<?php echo $this->translate('批量修改排序也可以到'); ?> <a href="<?php echo $this->url('tag/default',array('controller'=>'tag', 'action'=>'tagGroup')); ?>"><?php echo $this->translate('标签分组中进行修改'); ?></a>)</p>
        	<p class="pull-right">
			<button onclick="editAllTagSort();" class="btn btn-small btn-primary"><i class="icon-retweet icon-white"></i><?php echo $this->translate('批量更新标签排序'); ?></button>&nbsp;&nbsp;&nbsp;&nbsp;
            <a href="<?php echo $this->url('tag/default',array('action'=>'add','controller'=>'tag')); ?>" class="btn btn-small btn-primary"><i class="icon-plus icon-white"></i> <?php echo $this->translate('添加普通商品标签'); ?></a>&nbsp;
            <a href="<?php echo $this->myviewalias()->dbshopHelpUrl('goods_tag_set'); ?>" target="_blank" class="btn btn-small btn-info"><i class="icon-info-sign icon-white"></i> <?php echo $this->translate('查看帮助说明'); ?></a>
            </p>
        	</div>
			<form method="post" name="tag_update_form" id="tag_update_form">
            <table class="table table-hover">
            <thead style="background:#CCC;">
            	<tr>
					<th width="3%"><input type="checkbox" id="select_checkbox_state" onClick="selectCheckBox('tag_id','select_checkbox_state');"></th>
					<th width="8%"><?php echo $this->translate('标签排序'); ?></th>
					<th width="5%">ID</th>
					<th width="35%"><?php echo $this->translate('标签名称'); ?></th>
                    <th width="18%"><?php echo $this->translate('标签分组'); ?></th>
                    <th width="10%"><?php echo $this->translate('商品数量'); ?></th>
                    <th width="10%"><?php echo $this->translate('操作'); ?></th>
                </tr>
            </thead>
            <?php
			if ($this->tag_array) {
				foreach ($this->tag_array as $tag_val) {
					?>
					<tr>
						<td><input type="checkbox" name="tag_id[]" value="<?php echo $tag_val['tag_id']; ?>"></td>
						<td><input type="text" name="tag_sort[<?php echo $tag_val['tag_id']; ?>]" value="<?php echo $tag_val['tag_sort']; ?>" class="span8"></td>
						<td>
							<?php echo $tag_val['tag_id']; ?></td>
						<td>
							<?php echo $this->escapeHtml($tag_val['tag_name']); ?>
							<?php if(!empty($tag_val['tag_str'])) { ?>
							<label style="background-color: <?php echo $tag_val['tag_str']; ?>;height: 14px;width: 14px;border: 1px solid #E4E4E4;display:inline-block;line-height: 20px;vertical-align: middle;"></label>
							<?php } ?>
						</td>
						<td><?php echo($tag_val['tag_group_id'] == 0 ? $this->translate('无') : (!empty($tag_val['tag_group_mark']) ? '<strong>[' . $tag_val['tag_group_mark'] . ']</strong> ' : '') . $tag_val['tag_group_name']); ?></td>
						<td><?php echo $tag_val['tag_goods_num']; ?></td>
						<td>
							<a href="<?php echo $this->url('tag/default', array('action' => 'edit', 'tag_id' => $tag_val['tag_id'])); ?>"><?php echo $this->translate('编辑'); ?></a><span>|</span><a
									href="javascript:;"
									onclick="return tag_del_js(<?php echo $tag_val['tag_id']; ?>);"><?php echo $this->translate('删除'); ?></a>
						</td>
					</tr>
					<?php
				}
			}
			?>
            </table>
			</form>
            
<script>
//标签删除js
function tag_del_js(tag_id) {
	if(window.confirm('<?php echo $this->translate('您确实要删除该标签吗？'); ?>')) {
	$.post("<?php echo $this->url('tag/default',array('action'=>'del')); ?>",{tag_id:tag_id},
	function(data){
		if(data != 'false') {
			window.location.href='<?php echo $this->url('tag/default',array('action'=>'index')); ?>';
			return true;
		} else {
			alert('<?php echo $this->translate('标签删除失败！'); ?>');
		}
	});
	}
	return false;
}

function editAllTagSort() {
	var num = 0;
	$("input[name='tag_id[]']").each(function() {
		if (this.checked == true) {
			num++;
		}
	});
	if(num < 1) {
		alert('<?php echo $this->translate('请至少选择一条标签信息！'); ?>');
		return false;
	}
	$("#tag_update_form").submit();
}
</script>