    		<div style="height:30px;border-bottom:4px solid #DFDFDF;">
        	<p class="pull-left" style="font-size:16px; line-height:30px;"><strong><?php echo $this->translate('标签分组'); ?></strong></p>
        	<p class="pull-right">
            <a href="<?php echo $this->url('tag/default',array('action'=>'addTagGroup')); ?>" class="btn btn-small btn-primary"><i class="icon-plus icon-white"></i> <?php echo $this->translate('添加标签组'); ?></a>&nbsp;
            <a href="<?php echo $this->myviewalias()->dbshopHelpUrl('goods_tag_group_set'); ?>" target="_blank" class="btn btn-small btn-info"><i class="icon-info-sign icon-white"></i> <?php echo $this->translate('查看帮助说明'); ?></a>
            </p>
        	</div>
            <form action="<?php echo $this->url('tag/default',array('action'=>'allTagGroupUpdate')); ?>" name="submit_form" id="submit_form" method="post">
            <table class="table table-hover">
            <thead style="background:#CCC;">
            	<tr>
                    <th width="5%">ID</th>
                    <th width="30%"><?php echo $this->translate('标签组名称'); ?></th>
                    <th width="20%"><?php echo $this->translate('标签组标记'); ?></th>
                    <th width="15%"><?php echo $this->translate('用于(高级)商品规格'); ?></th>
                    <th width="15%"><?php echo $this->translate('标签组排序'); ?></th>
                    <th width="15%"><?php echo $this->translate('操作'); ?></th>
                </tr>
            </thead>
            <?php
			if ($this->tag_group) {
				foreach ($this->tag_group as $group_val) {
			?>            
            <tr>
            	<td><?php echo $group_val['tag_group_id']; ?></td>
            	<td><?php echo $this->escapeHtml($group_val['tag_group_name']); ?></td>
                <td><?php echo !empty($group_val['tag_group_mark']) ? $this->escapeHtml($group_val['tag_group_mark']) : $this->translate('无'); ?></td>
                <td><?php echo ($group_val['is_goods_spec'] == 1 ? $this->translate('是') : $this->translate('否')); ?></td>
                <td><input type="text" class="span5" name="tag_group_sort[<?php echo $group_val['tag_group_id']; ?>]" value="<?php echo $group_val['tag_group_sort']; ?>"></td>
            	<td><a href="<?php echo $this->url('tag/goods_tag_group',array('action'=>'editTagGroup','tag_group_id'=>$group_val['tag_group_id'])); ?>"><?php echo $this->translate('编辑'); ?></a><span>|</span><a href="javascript:;" onclick="return group_del_js(<?php echo $group_val['tag_group_id']; ?>);"><?php echo $this->translate('删除'); ?></a></td>  
            </tr>
            <?php
				}
			}
			?>
                <tr>
                    <td colspan="5" style="background: #FFF">
                        <div class="pull-left span6" style="height: 30px; line-height: 30px;">
                            <button type="submit" class="btn btn-small btn-primary"><i class="icon-tasks icon-white"></i> <?php echo $this->translate('批量修改'); ?></button>
                        </div>
                    </td>
                </tr>
            </table>
            </form>
            
<script>
//标签组删除js
function group_del_js(group_id) {
	if(window.confirm('<?php echo $this->translate('您确实要删除该标签组吗？'); ?>')) {
	$.post("<?php echo $this->url('tag/default',array('action'=>'delTagGroup')); ?>",{tag_group_id:group_id},
	function(data){
		if(data != 'false') {
			window.location.href='<?php echo $this->url('tag/default',array('action'=>'tagGroup')); ?>';
			return true;
		} else {
			alert('<?php echo $this->translate('标签组删除失败，标签组下存在标签！'); ?>');
		}
	});
	}
	return false;
}
</script>