    		<div id="sticky_navigation" style="height:30px;border-bottom:4px solid #DFDFDF;">
        	<p class="pull-left" style="font-size:16px; line-height:30px;"><strong><?php echo $this->translate('管理管理员'); ?></strong></p>
        	<p class="pull-right">
            <a href="<?php echo $this->url('admin/default',array('action'=>'adminadd','controller'=>'admin')); ?>" class="btn btn-small btn-primary"><i class="icon-plus icon-white"></i> <?php echo $this->translate('添加新管理员'); ?></a>&nbsp;
            <a href="<?php echo $this->myviewalias()->dbshopHelpUrl('admin_set'); ?>" target="_blank" class="btn btn-small btn-info"><i class="icon-info-sign icon-white"></i> <?php echo $this->translate('查看帮助说明'); ?></a>
            </p>
        	</div>
            <table class="table table-hover">
            <thead style="background:#CCC;">
            	<tr>
                    <th width="5%">ID</th>
                    <th width="20%"><?php echo $this->translate('管理员名称'); ?></th>
                    <th width="17%"><?php echo $this->translate('电子邮件'); ?></th>
                    <th width="12%"><?php echo $this->translate('管理员组'); ?></th>
                    <th width="10%"><?php echo $this->translate('管理员加入时间'); ?></th>
                    <th width="6%"><?php echo $this->translate('操作'); ?></th>
                </tr>
            </thead>
            <?php 
            if($this->admin_list) {
            foreach ($this->admin_list as $admin_value) { ?>
            <tr>
            	<td><?php echo $admin_value['admin_id']; ?></td>
            	<td><?php echo $this->escapeHtml($admin_value['admin_name']); ?></td>
            	<td><?php echo $admin_value['admin_email']; ?></td>
            	<td><a href="<?php echo $this->url('admin/default/admin_group_id',array('action'=>'editgroup','controller'=>'admin','admin_group_id'=>$admin_value['admin_group_id'])); ?>"><?php echo $this->escapeHtml($admin_value['admin_group_name']); ?></a></td>
            	<td><?php echo date("Y-m-d H:i:s",$admin_value['admin_add_time']); ?></td>
            	<td>
				<?php if($admin_value['admin_id'] == 1 and $this->myviewalias()->returnAuth('admin_id') != 1) {} else { ?>
            	<a href="<?php echo $this->url('admin/default/admin_id',array('action'=>'adminedit','controller'=>'admin','admin_id'=>$admin_value['admin_id'])); ?>"><?php echo $this->translate('编辑'); ?></a>
            	<?php } ?>

				<?php if ($admin_value['admin_id'] != 1) { ?>
            	<span>|</span>
                <a href="javascript:;" onclick="return admin_del_js(<?php echo $admin_value['admin_id']; ?>);"><?php echo $this->translate('删除'); ?></a>
            	<?php } ?>
            	</td>  
            </tr>
            <?php 
                    }
                } ?>
            </table>
<script>
//管理员删除js
function admin_del_js(admin_id) {
	if(window.confirm('<?php echo $this->translate('您确实要删除该管理员吗？'); ?>')) {
		$.post("<?php echo $this->url('admin/default',array('action'=>'admindel','controller'=>'admin')); ?>",{admin_id:admin_id},
		function(data){
			if(data != 'false') {
				window.location.href='<?php echo $this->url('admin/default',array('action'=>'administrator','controller'=>'admin')); ?>';
				return true;
			} else {
				alert('<?php echo $this->translate('管理员删除失败！'); ?>');
			}
		});
	}
	return false;
}
</script>