    		<div id="sticky_navigation" style="height:30px;border-bottom:4px solid #DFDFDF;">
        	<p class="pull-left" style="font-size:16px; line-height:30px;"><strong><?php echo $this->translate('管理管理员组'); ?></strong></p>
        	<p class="pull-right">
            <a href="<?php echo $this->url('admin/default',array('action'=>'groupadd','controller'=>'admin')); ?>" class="btn btn-small btn-primary"><i class="icon-plus icon-white"></i> <?php echo $this->translate('添加管理员组'); ?></a>&nbsp;
            <a href="<?php echo $this->myviewalias()->dbshopHelpUrl('admin_group_set'); ?>" target="_blank" class="btn btn-small btn-info"><i class="icon-info-sign icon-white"></i> <?php echo $this->translate('查看帮助说明'); ?></a>
            </p>
        	</div>
            <table class="table table-hover">
            <thead style="background:#CCC;">
            	<tr>
                    <th width="5%">ID</th>
                    <th width="75%"><?php echo $this->translate('管理员组名称'); ?></th>
                    <th width="20%"><?php echo $this->translate('操作'); ?></th>
                </tr>
            </thead>
            <?php
			if ($this->group_array) {
				foreach ($this->group_array as $group_val) {
			?>            
            <tr>
            	<td><?php echo $group_val['admin_group_id']; ?></td>
            	<td><?php echo $this->escapeHtml($group_val['admin_group_name']); ?></td>
            	<td><a href="<?php echo $this->url('admin/default/admin_group_id',array('action'=>'editgroup','admin_group_id'=>$group_val['admin_group_id'])); ?>"><?php echo $this->translate('编辑'); ?></a>
                <?php if($group_val['admin_group_id'] != 1) { ?>
                <span>|</span>
                <a href="javascript:;" onclick="return group_del_js(<?php echo $group_val['admin_group_id']; ?>);"><?php echo $this->translate('删除'); ?></a>
                <?php } ?>
                </td>  
            </tr>
            <?php
				}
			}
			?>
            </table>
            
<script>
function group_del_js(admin_group_id) {
	if(window.confirm('<?php echo $this->translate('您确实要删除该管理员组吗？'); ?>')) {
	$.post("<?php echo $this->url('admin/default',array('action'=>'groupdel','controller'=>'admin')); ?>",{admin_group_id:admin_group_id},
	function(data){
		if(data != 'false') {
			window.location.href='<?php echo $this->url('admin/default',array('action'=>'admingroup','controller'=>'admin')); ?>';
			return true;
		} else {
			alert('<?php echo $this->translate('管理员组删除失败，该客户组下已经有管理员存在，需要先删除组下管理员信息！'); ?>');
		}
	});
	}
	return false;
}
</script>