    		<div id="sticky_navigation" style="height:30px;border-bottom:4px solid #DFDFDF;">
        	<p class="pull-left" style="font-size:16px; line-height:30px;"><strong><?php echo $this->translate('友情链接管理'); ?></strong></p>
        	<p class="pull-right">
            <a href="<?php echo $this->url('links/default',array('action'=>'add')); ?>" class="btn btn-small btn-primary"><i class="icon-plus icon-white"></i> <?php echo $this->translate('添加友情链接'); ?></a>&nbsp;
            <a href="<?php echo $this->myviewalias()->dbshopHelpUrl('link_set'); ?>" target="_blank" class="btn btn-small btn-info"><i class="icon-info-sign icon-white"></i> <?php echo $this->translate('查看帮助说明'); ?></a>
            </p>
        	</div>
            <form action="<?php echo $this->url('links/default',array('action'=>'allUpdate')); ?>" name="links_form" id="links_form" method="post">
            <table class="table table-hover">
            <thead style="background:#CCC;">
            	<tr>
                    <th width="5%">ID</th>
                    <th width="20%"><?php echo $this->translate('网站名称'); ?></th>
                    <th width="12%"><?php echo $this->translate('网站logo'); ?></th>
                    <th width="5%"><?php echo $this->translate('排序'); ?></th>
                    <th width="5%"><?php echo $this->translate('状态'); ?></th>
                    <th width="8%"><?php echo $this->translate('操作'); ?></th>
                </tr>
            </thead>
            <?php if($this->links_list) { foreach ($this->links_list as $links_value) { ?>
            <tr>
            	<td><?php echo $links_value['links_id']; ?></td>
            	<td><?php echo $this->escapeHtml($links_value['links_webname']); ?></td>
                <td><?php if ($links_value['links_logo'] == '') { echo $this->translate('无图片'); } else { ?><img src="<?php echo $this->basePath($links_value['links_logo']); ?>"  style="border:1px solid #DDDDDD;height:30px;" /><?php } ?></td>
                <td><input type="text" class="span8" name="links_sort[<?php echo $links_value['links_id']; ?>]" value="<?php echo $links_value['links_sort']; ?>"></td>
                <td><?php echo ($links_value['links_state'] == 1 ? $this->translate('启用') : $this->translate('禁用')); ?></td>
            	<td><a href="<?php echo $this->url('links/default/links_id',array('action'=>'edit','links_id'=>$links_value['links_id'])); ?>"><?php echo $this->translate('编辑'); ?></a><span>|</span><a href="javascript:;" onclick="return links_del_js(<?php echo $links_value['links_id']; ?>);"><?php echo $this->translate('删除'); ?></a></td>  
            </tr>
            <?php
				}
			?>
                <tr>
                    <td colspan="6" style="background: #FFF">
                        <div class="pull-left span6" style="height: 30px; line-height: 30px;">
                            <button type="submit" class="btn btn-small btn-primary"><i class="icon-tasks icon-white"></i> <?php echo $this->translate('批量修改'); ?></button>
                        </div>
                    </td>
                </tr>
            <?php
            }
            ?>
            </table>
            </form>
            
<script>
//友情链接删除js
function links_del_js(links_id) {
	if(window.confirm('<?php echo $this->translate('您确实要删除该友情链接吗？'); ?>')) {
	$.post("<?php echo $this->url('links/default',array('action'=>'del')); ?>",{links_id:links_id},
	function(data){
		if(data != 'false') {
			window.location.href='<?php echo $this->url('links/default'); ?>';
			return true;
		} else {
			alert('<?php echo $this->translate('友情链接删除失败！'); ?>');
		}
	});
	}
	return false;
}
</script>