<?php if ($this->goods_ask_list->getTotalItemCount() > 0) { ?>
<ul class="media-list">
  <?php foreach ($this->goods_ask_list as $ask_value) { ?>
  <li class="media">
    <div class="media-body well well-small">
      <h4 class="media-heading"><?php echo $this->frontwebsite()->userNameHide($ask_value['ask_writer']); ?> <small><?php echo date("Y-m-d H:i:s", $ask_value['ask_time']); ?></small></h4>
      <p><?php echo $this->escapeHtml($ask_value['ask_content']); ?></p>
      <?php if($ask_value['reply_ask_content'] != '') { ?>
      <hr />
      <h4><?php echo $this->translate('店主'); ?> <small><?php echo date("Y-m-d H:i:s", $ask_value['reply_ask_time']); ?></small></h4>
      <p><?php echo $this->escapeHtml($ask_value['reply_ask_content']); ?></p>
      <?php } ?>
    </div>
  </li>
  <?php } ?>
  <li style="padding-bottom:8px;"> <?php echo ( count($this->goods_ask_list) > 0 ) ? $this->paginationControl($this->goods_ask_list, 'Sliding', 'site/ajax-dbpage',array('page_url'=>$this->url('frontgoods/default',array('action'=>'goodsAsk','goods_id'=>$this->goods_id,'class_id'=>$this->class_id)), 'ajaxFunction'=>'ask_ajax_list')) : ""; ?> </li>
</ul>
<?php } else { ?>
<div class="alert alert-info"> <strong><?php echo $this->translate('该商品暂无咨询信息！'); ?></strong></div>
<?php } ?>
