    		<div id="sticky_navigation" style="height:30px;border-bottom:4px solid #DFDFDF;">
        	<p class="pull-left" style="font-size:16px; line-height:30px;"><strong><?php echo $this->translate('积分规则'); ?></strong></p>
        	<p class="pull-right">
        	<a href="<?php echo $this->url('integral/default',array('action'=>'addIntegralRule')); ?>" class="btn btn-small btn-primary"><i class="icon-plus icon-white"></i> <?php echo $this->translate('添加新规则'); ?></a>&nbsp;
        	<a href="<?php echo $this->myviewalias()->dbshopHelpUrl('user_integral_set'); ?>" target="_blank" class="btn btn-small btn-info"><i class="icon-info-sign icon-white"></i> <?php echo $this->translate('查看帮助说明'); ?></a>
        	</p>
        	</div>
            <table class="table table-hover">
            <thead style="background:#CCC;">
            	<tr>
                    <th width="20%"><?php echo $this->translate('积分规则名称'); ?></th>
                    <th width="35%"><?php echo $this->translate('积分规则描述'); ?></th>
                    <th width="20%"><?php echo $this->translate('有效时间'); ?></th>
                    <th width="10%"><?php echo $this->translate('状态'); ?></th>
                    <th width="15%"><?php echo $this->translate('操作'); ?></th>
                </tr>
            </thead>
            <?php
			if ($this->integral_rule_list) {
				foreach ($this->integral_rule_list as $rule_val) {
			?>
            <tr>
            	<td><?php echo $this->escapeHtml($rule_val['integral_rule_name']); ?></td>
                <td><?php echo $rule_val['integral_rule_info']; ?></td>
                <td><?php
                $start_time = empty($rule_val['integral_rule_start_time']) ? '' : date("Y-m-d H:i", $rule_val['integral_rule_start_time']);
				$end_time   = empty($rule_val['integral_rule_end_time']) ? '' : date("Y-m-d H:i", $rule_val['integral_rule_end_time']);
				if($start_time == '' and $end_time == '') {
					$start_and_end_time = $this->translate('长期有效');
				} elseif ($end_time != '' and time() > $rule_val['integral_rule_end_time']) {
					$start_and_end_time = '<font color="#FF0000">' . $this->translate('已经过期') . '</font>';
				} else {
					$start_and_end_time = (empty($start_time) ? $this->translate('无') : $start_time) . ' / ' . (empty($end_time) ? $this->translate('无') : $end_time);
				}

				echo $start_and_end_time; ?></td>
                <td><?php echo $rule_val['integral_rule_state'] == 1 ? $this->translate('开启') :$this->translate('关闭'); ?></td>
            	<td style="vertical-align:middle">
                    <a href="<?php echo $this->url('integral/default/integral_rule_id',array('action'=>'editIntegralRule','integral_rule_id'=>$rule_val['integral_rule_id'])); ?>"><?php echo $this->translate('编辑'); ?></a>
                    <span>|</span>
                    <a href="<?php echo $this->url('integral/default/integral_rule_id',array('action'=>'delIntegralRule', 'integral_rule_id'=>$rule_val['integral_rule_id'])); ?>" onclick="return window.confirm('<?php echo $this->translate('您确实要删除该积分规则吗？'); ?>');"><?php echo $this->translate('删除'); ?></a>
                </td>  
            </tr>
            <?php
				}
			} else {
			?>
			<tr><td colspan="5"><?php echo $this->translate('暂无积分规则'); ?></td></tr>
			<?php } ?> 
            </table>