    		<div id="sticky_navigation" style="height:30px;border-bottom:4px solid #DFDFDF;">
        	<p class="span4 pull-left" style="font-size:16px; line-height:30px;"><strong><?php echo $this->translate('积分类型'); ?></strong></p>
        	<p class="span8 text-right">
            <a href="<?php echo $this->myviewalias()->dbshopHelpUrl('user_integral_type'); ?>" target="_blank" class="btn btn-small btn-info"><i class="icon-info-sign icon-white"></i> <?php echo $this->translate('查看帮助说明'); ?></a>
            </p>
        	</div>
            <table class="table table-hover">
            <thead style="background:#CCC;">
            	<tr>
                    <th width="35%"><?php echo $this->translate('积分类型名称'); ?></th>
                    <th width="10%"><?php echo $this->translate('初始积分'); ?></th>
                    <th width="30%"><?php echo $this->translate('每100积分可抵现金（基础货币）数'); ?></th>
                    <th width="15%"><?php echo $this->translate('操作'); ?></th>
                </tr>
            </thead>
            <?php if($this->user_integral_type_list) foreach ($this->user_integral_type_list as $type_value) { ?>
            <tr>
            	<td><?php echo $this->escapeHtml($type_value['integral_type_name']); ?></td>
                <td><?php echo $type_value['default_integral_num']; ?></td>
                <td><?php echo $type_value['integral_type_mark'] == 'integral_type_1' ? $type_value['integral_currency_con'] : $this->translate('不可用(只消费积分可用)'); ?></td>
                <td><a href="<?php echo $this->url('integral/default/integral_type_id',array('action'=>'integralTypeEdit', 'integral_type_id'=>$type_value['integral_type_id'])); ?>"><?php echo $this->translate('编辑'); ?></a></td>
            </tr>
            <?php
				}
			?>
        </table>