<script>
var shop_base_url = '<?php echo $this->basePath('/public/editor/ueditor/'); ?>';
</script>
<script type="text/javascript" charset="utf-8" src="<?php echo $this->basePath('/public/editor/ueditor/editor_config.js'); ?>"></script>
<script type="text/javascript" charset="utf-8" src="<?php echo $this->basePath('/public/editor/ueditor/editor_all_min.js'); ?>"></script>
<script>
//实例化编辑器
<?php if($this->edit_array) {
			echo "var editorOption = {";
			if(is_array($this->edit_config) and !empty($this->edit_config)) {
				echo @implode(',',$this->edit_config);
			} else {
				echo "initialFrameWidth:'100%',initialFrameHeight:500,autoHeightEnabled:false";
			}
			echo ",catchRemoteImageEnable:false};";

	foreach ($this->edit_array as $key => $value) {
		?>
		var ue<?php echo $key; ?> = new UE.ui.Editor(editorOption);
		ue<?php echo $key; ?>.render('<?php echo $value; ?>');
		<?php
	}
} ?>
</script>