<div class="header_menu">
    <div class="container">
        <div class="header-nav clearfix">
            <?php echo $this->partial('site/headermenu'); ?>
        </div>
    </div>
</div>
</div>

<div class="container breadcrumbs">
    <a href="<?php echo $this->url('shopfront/default'); ?>"><?php echo $this->translate('首页'); ?></a><span class="sep">/</span>
    <span><?php echo $this->escapeHtml($this->single_article_info->single_article_title); ?></span>
</div>

<div class="container clearfix">
    <div class="row">

        <div class="row exchange">
            <!-- .span4 END -->
            <div class="span20 exchange-right">

                <div class="xm-box exchange service-right">
                    <div class="box-hd">
                        <h2 class="title"><?php echo $this->escapeHtml($this->single_article_info->single_article_title . $this->single_article_info->single_article_title_extend); ?></h2>
                    </div>
                    <div class="bd">
                        <?php
                        $goods_share_info = $this->frontwebsite()->getDbshopGoodsShare();
                        if(!empty($goods_share_info['share_type'])) {
                            echo "<script>var dbshop_baidushare_path='". $this->basePath('/public/js/baiduShare/')."';</script>";
                        ?>
                        <p>
                            <?php echo $goods_share_info['share_code']; ?>
                        </p>
                        <br>
                        <?php } ?>
                        <div style="font-size:16px;" class="edit_table_css">
                            <?php echo $this->single_article_info->single_article_body; ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>