    		<div id="sticky_navigation" style="height:30px;border-bottom:4px solid #DFDFDF;">
        	<p class="pull-left" style="font-size:16px; line-height:30px;"><strong><?php echo $this->translate('导航设置'); ?></strong></p>
        	<p class="pull-right">
            <a href="<?php echo $this->url('navigation/default',array('action'=>'add')); ?>" class="btn btn-small btn-primary"><i class="icon-plus icon-white"></i> <?php echo $this->translate('添加导航链接'); ?></a>&nbsp;
            <a href="<?php echo $this->myviewalias()->dbshopHelpUrl('navigation_set'); ?>" target="_blank" class="btn btn-small btn-info"><i class="icon-info-sign icon-white"></i> <?php echo $this->translate('查看帮助说明'); ?></a>
            </p>
        	</div>
            <form action="<?php echo $this->url('navigation/default',array('action'=>'allUpdate')); ?>" name="navigation_form" id="navigation_form" method="post">
            <table class="table table-hover">
            <thead style="background:#CCC;">
            	<tr>
                    <th width="4%">ID</th>
                    <th width="8%"><?php echo $this->translate('导航标题'); ?></th>
                    <th width="20%"><?php echo $this->translate('导航地址'); ?></th>
                    <th width="5%"><?php echo $this->translate('位置'); ?></th>
                    <th width="5%"><?php echo $this->translate('新窗口打开'); ?></th>
                    <th width="5%"><?php echo $this->translate('排序'); ?></th>
                    <th width="5%"><?php echo $this->translate('操作'); ?></th>
                </tr>
            </thead>
            <?php if($this->navigation_list) { foreach ($this->navigation_list as $navigation_value) { ?>
            <tr>
            	<td><?php echo $navigation_value['navigation_id']; ?></td>
            	<td><?php echo $this->escapeHtml($navigation_value['navigation_title']); ?></td>
                <td><?php echo $navigation_value['navigation_url']; ?></td>
                <td><?php if($navigation_value['navigation_type']==1) { echo $this->translate('顶部'); } elseif ($navigation_value['navigation_type']==2) { echo $this->translate('中部'); } elseif ($navigation_value['navigation_type']==3) { echo $this->translate('底部'); }?></td>
                <td><?php if($navigation_value['navigation_new_window']==1) echo $this->translate('是'); else echo $this->translate('否'); ?></td>
                <td><input type="text" class="span8" name="navigation_sort[<?php echo $navigation_value['navigation_id']; ?>]" value="<?php echo $navigation_value['navigation_sort']; ?>"></td>
            	<td><a href="<?php echo $this->url('navigation/default/navigation_id',array('action'=>'edit','navigation_id'=>$navigation_value['navigation_id'])); ?>"><?php echo $this->translate('编辑'); ?></a><span>|</span><a href="javascript:;" onclick="return navigation_del_js(<?php echo $navigation_value['navigation_id']; ?>);"><?php echo $this->translate('删除'); ?></a></td>  
            </tr>
            <?php
				}
			?>
                <tr>
                    <td colspan="7" style="background: #FFF">
                        <div class="pull-left span6" style="height: 30px; line-height: 30px;">
                            <button type="submit" class="btn btn-small btn-primary"><i class="icon-tasks icon-white"></i> <?php echo $this->translate('批量修改'); ?></button>
                        </div>
                    </td>
                </tr>
            <?php } ?>
            </table>
            </form>
            
<script>
//导航删除js
function navigation_del_js(navigation_id) {
	if(window.confirm('<?php echo $this->translate('您确实要删除该导航吗？'); ?>')) {
	$.post("<?php echo $this->url('navigation/default',array('action'=>'del')); ?>",{navigation_id:navigation_id},
	function(data){
		if(data != 'false') {
			window.location.href='<?php echo $this->url('navigation/default'); ?>';
			return true;
		} else {
			alert('<?php echo $this->translate('导航删除失败！'); ?>');
		}
	});
	}
	return false;
}
</script>