<div id="myCarousel{randid}" class="well carousel slide" style="padding: 0 0 0 0;">
            <div class="carousel-inner">
            <dbshop>
            <div class="{active}item">
            <a target="_blank" href="{ad_url}"><img src="{image}"></a>
                <div class="carousel-caption">
                  <p>{ad_body}</p>
                </div>
            </div>
            <dbshop>
            </div>
            <a class="carousel-control left" href="#myCarousel{randid}" data-slide="prev">&lsaquo;</a>
            <a class="carousel-control right" href="#myCarousel{randid}" data-slide="next">&rsaquo;</a>
            </div>
<script>
    $('.carousel').carousel();
</script>