<style>
.admin_system_well {
	padding:8px;
	margin-bottom:15px;
}
</style>
<div id="update_template_message">

</div>
<div class="row-fluid">
	<div class="span12 well well-small" style="padding-bottom:0px; margin-bottom:8px;">
    <p><strong><?php echo $this->translate('快速设置'); ?>：</strong>
    <a href="<?php echo $this->url('system/default',array('controller'=>'system')); ?>" class="btn btn-primary"><i class="icon-wrench icon-white"></i> <?php echo $this->translate('系统设置'); ?></a>&nbsp;<i class="icon-arrow-right"></i>
    <a href="<?php echo $this->url('payment/default',array('action'=>'index')); ?>" class="btn btn-primary"><i class="icon-shopping-cart icon-white"></i> <?php echo $this->translate('支付设置'); ?></a>&nbsp;<i class="icon-arrow-right"></i>
    <a href="<?php echo $this->url('region/default',array('controller'=>'region')); ?>" class="btn btn-primary"><i class="icon-globe icon-white"></i> <?php echo $this->translate('地区设置'); ?></a>&nbsp;<i class="icon-arrow-right"></i>
    <a href="<?php echo $this->url('express/default',array('action'=>'index')); ?>" class="btn btn-primary"><i class="icon-plane icon-white"></i> <?php echo $this->translate('配送设置'); ?></a>&nbsp;<i class="icon-arrow-right"></i>
    <a href="<?php echo $this->url('class/default',array('controller'=>'class')); ?>" class="btn btn-primary"><i class="icon-th-list icon-white"></i> <?php echo $this->translate('添加商品分类'); ?></a>&nbsp;<i class="icon-arrow-right"></i>
    <a href="<?php echo $this->url('goods/default',array('controller'=>'goods')); ?>" class="btn btn-primary"><i class="icon-plus icon-white"></i> <?php echo $this->translate('添加商品'); ?></a>&nbsp;<i class="icon-arrow-right"></i>
    <a href="<?php echo $this->url('shopfront/default'); ?>" target="_blank" class="btn btn-success"><i class="icon-ok icon-white"></i> <?php echo $this->translate('完成'); ?></a>&nbsp;
        <a href="<?php echo $this->myviewalias()->dbshopHelpUrl('system_quick_set'); ?>" target="_blank"  style="margin-right:10px;" class="btn btn-info pull-right"><i class="icon-info-sign icon-white"></i> <?php echo $this->translate('帮助说明'); ?></a>
    </p>
    </div>
</div>
<div class="row-fluid">
    <div class="span12 well well-small" style="padding-bottom:0px; margin-bottom:8px;">
        <p><strong><?php echo $this->translate('扩展设置'); ?>：</strong>
            <a href="<?php echo $this->url('plugin/default',array('action'=>'install')); ?>" class="btn btn-primary"><?php echo $this->translate('插件市场'); ?></a>&nbsp;&nbsp;
            <a href="<?php echo $this->url('template/default', array('controller'=>'Template', 'action'=>'installTemplate')); ?>" class="btn btn-primary"><?php echo $this->translate('安装电脑模板'); ?></a>&nbsp;&nbsp;
            <a href="<?php echo $this->url('phonetemplate/default', array('action'=>'installPhoneTemplate')); ?>" class="btn btn-primary"><?php echo $this->translate('安装手机模板'); ?></a>&nbsp;&nbsp;

            <a href="http://help.dbshop.net/#.E5.89.8D.E5.8F.B0.E6.A8.A1.E6.9D.BF.E8.AE.BE.E7.BD.AE.E6.95.99.E7.A8.8B" class="btn btn-info" target="_blank"><?php echo $this->translate('前台首页设置'); ?></a>&nbsp;
        </p>
    </div>
</div>
<div class="row-fluid">
  <div class="span6">
        <table class="table table-bordered table-condensed">
            <thead class="admin_add_header_well">
            <th colspan="4"><?php echo $this->translate('订单信息'); ?></th>
            </thead>
        	<tr>
            	<td width="20%"><strong><?php echo $this->translate('待付款订单'); ?></strong>：</td>
                <td width="30%"><a href="<?php echo $this->url('orders/default', array(), array('query'=>array('order_state'=>10))); ?>"><?php echo $this->order_no_payment; ?></a></td>
            	<td width="20%"><strong><?php echo $this->translate('已付款订单'); ?></strong>：</td>
                <td width="30%"><a href="<?php echo $this->url('orders/default', array(), array('query'=>array('order_state'=>20))); ?>"><?php echo $this->order_yes_payment; ?></a></td>
            </tr>
            <tr>
                <td><strong><?php echo $this->translate('待发货订单'); ?></strong>：</td>
                <td><a href="<?php echo $this->url('orders/default', array(), array('query'=>array('order_state'=>30))); ?>"><?php echo $this->order_no_send; ?></a></td>
            	<td><strong><?php echo $this->translate('待收货订单'); ?></strong>：</td>
                <td><a href="<?php echo $this->url('orders/default', array(), array('query'=>array('order_state'=>40))); ?>"><?php echo $this->order_no_finish; ?></a></td>
            </tr>
            <tr>
                <td><strong><?php echo $this->translate('已完成订单'); ?></strong>：</td>
                <td><a href="<?php echo $this->url('orders/default', array(), array('query'=>array('order_state'=>60))); ?>"><?php echo $this->order_finish; ?></a></td>
            	<td><strong><?php echo $this->translate('已取消订单'); ?></strong>：</td>
                <td><a href="<?php echo $this->url('orders/default', array(), array('query'=>array('order_state'=>0))); ?>"><?php echo $this->order_cancel; ?></a></td>
            </tr>
            <tr>
                <td><strong><?php echo $this->translate('待处理退货'); ?></strong>：</td>
                <td><a href="<?php echo $this->url('orders/default', array('action'=>'refund', 'controller'=>'Orders'), array('query'=>array('refund_state'=>0))); ?>"><?php echo $this->refund_n; ?></a></td>
                <td><strong><?php echo $this->translate('已处理退货'); ?></strong>：</td>
                <td><a href="<?php echo $this->url('orders/default', array('action'=>'refund', 'controller'=>'Orders')); ?>"><?php echo $this->refund_y; ?></a></td>
            </tr>
        </table>
  </div>
  <div class="span6">
        <table class="table table-bordered table-condensed">
            <thead class="admin_add_header_well">
            <th colspan="4"><?php echo $this->translate('商品信息'); ?></th>
            </thead>
        	<tr>
            	<td width="20%"><strong><?php echo $this->translate('上架商品'); ?></strong>：</td><td width="30%"><?php echo $this->open_goods; ?></td><td width="20%"><strong><?php echo $this->translate('下架商品'); ?></strong>：</td><td width="30%"><?php echo $this->close_goods; ?></td>
            </tr>
            <tr>
            	<td><strong><?php echo $this->translate('缺货商品'); ?></strong>：</td><td><?php echo ($this->out_stock_goods > 0 ? '<a href="'.$this->url('goods/default',array('action'=>'index','controller'=>'goods'), array('query'=>array('goods_state'=>-1))).'">'.$this->out_stock_goods.'</a>' : 0); ?></td><td><strong><?php echo $this->translate('销售商品'); ?></strong>：</td><td><?php echo $this->sell_goods; ?></td>
            </tr>
            <tr>
                <td><strong><?php echo $this->translate('优惠商品'); ?></strong>：</td><td><?php echo ($this->preferential_goods > 0 ? '<a href="'.$this->url('goods/default',array('action'=>'index','controller'=>'goods'), array('query'=>array('goods_preferential'=>1))).'">'.$this->preferential_goods.'</a>' : 0); ?></td><td><strong><?php echo $this->translate('商品分类'); ?></strong>：</td><td><?php echo $this->goods_class_num; ?></td>
            </tr>
        </table>
  </div>
</div>
<div class="row-fluid">
  <div class="span6">
        <table class="table table-bordered table-condensed">
            <thead class="admin_add_header_well">
            <th colspan="4"><?php echo $this->translate('会员信息'); ?></th>
            </thead>
        	<tr>
            	<td width="20%"><strong><?php echo $this->translate('会员总数'); ?></strong>：</td><td width="30%"><?php echo $this->user_count; ?></td><td width="20%"><strong><?php echo $this->translate('购买过商品会员'); ?></strong>：</td><td width="30%"><?php echo $this->buy_user_count; ?></td>
            </tr>
            <tr>
            	<td><strong><?php echo $this->translate('待审核会员'); ?></strong>：</td><td><?php echo $this->auth_count; ?></td><td><strong><?php echo $this->translate('已关闭会员'); ?></strong>：</td><td><?php echo $this->close_count; ?></td>
            </tr>
        </table>
  </div>
  <div class="span6">
        <table class="table table-bordered table-condensed">
            <thead class="admin_add_header_well">
            <th colspan="4"><?php echo $this->translate('其他信息'); ?></th>
            </thead>
        	<tr>
            	<td width="20%"><strong><?php echo $this->translate('商品评价'); ?></strong>：</td>
                <td width="30%"><a href="<?php echo $this->url('comment/default',array('controller'=>'comment')); ?>"><?php echo $this->comment_count; ?></a></td>
                <td width="20%"><strong><?php echo $this->translate('商品咨询'); ?></strong>：</td>
                <td width="30%"><a href="<?php echo $this->url('ask/default'); ?>"><?php echo $this->ask_count; ?></a></td>
            </tr>
        </table>
  </div>
</div>

<div class="row-fluid">
	<div class="span6" id="news_table">
    		<table class="table table-bordered">
                <thead class="admin_add_header_well">
                <th><?php echo $this->translate('DBShop新闻动态'); ?></th>
                </thead>
    		    <tr>
                    <td>
                        <img src="<?php echo $this->basePath('public/admin/img/update_loading.gif'); ?>" border="0" /> <strong><?php echo $this->translate('动态新闻加载中……'); ?></strong>
                    </td>
    		    </tr>
            </table>
    </div>
    <div class="span6">
        <table class="table table-bordered table-condensed">
            <thead class="admin_add_header_well">
            <th colspan="4"><?php echo $this->translate('DBShop系统信息'); ?></th>
            </thead>
            <tr>
                <td width="20%"><strong><?php echo $this->translate('DBShop版本'); ?></strong>：</td><td width="30%"><?php echo $this->dbshop_version; ?></td><td width="20%"><strong><?php echo $this->translate('编码'); ?></strong>：</td><td width="30%"><?php echo $this->dbshop_charset; ?></td>
            </tr>
            <tr>
                <td><strong><?php echo $this->translate('安装日期'); ?></strong>：</td><td><?php echo $this->dbshop_install_time; ?></td><td><strong><?php echo $this->translate('更新日期'); ?></strong>：</td><td><?php echo $this->dbshop_update_time; ?></td>
            </tr>
            <tr>
                <td><strong><?php echo $this->translate('PHP版本'); ?></strong>：</td><td><?php echo PHP_VERSION; ?></td><td><strong><?php echo $this->translate('官方网站'); ?></strong>：</td><td><a href="http://www.dbshop.net/" target="_blank">http://www.dbshop.net/</a></td>
            </tr>
            <tr>
                <td><strong><?php echo $this->translate('使用教程'); ?></strong>：</td><td><a href="http://help.dbshop.net/" target="_blank">http://help.dbshop.net/</a></td><td><strong><?php echo $this->translate('官方论坛'); ?></strong>：</td><td><a href="http://bbs.dbshop.net/" target="_blank">http://bbs.dbshop.net/</a></td>
            </tr>
            <tr>
                <td><strong><?php echo $this->translate('官方QQ群'); ?></strong>：</td><td><strong>315077108</strong></td>
                <td style="line-height: 25px;"><strong><?php echo $this->translate('授权信息'); ?></strong>：</td><td id="auth_html"></td>
            </tr>
        </table>
    </div>
</div>