<div id="sticky_navigation" style="height:30px;border-bottom:4px solid #DFDFDF;">
    <p class="pull-left" style="font-size:16px; line-height:30px;"><strong><?php echo $this->translate('商品设置'); ?></strong></p>
    <p class="pull-right">
        <a href="<?php echo $this->url('admintheme/default'); ?>" class="btn btn-small"><i class="icon-arrow-left"></i> <?php echo $this->translate('返回专题列表'); ?></a>&nbsp;
        <a href="<?php echo $this->myviewalias()->dbshopHelpUrl('theme_set'); ?>" target="_blank" class="btn btn-small btn-info"><i class="icon-info-sign icon-white"></i> <?php echo $this->translate('查看帮助说明'); ?></a>
    </p>
</div>
<table class="table table-hover">
    <thead style="background:#CCC;">
    <tr>
        <th width="4%">ID</th>
        <th width="20%"><?php echo $this->translate('类型名称'); ?></th>
        <th width="20%"><?php echo $this->translate('商品标记'); ?></th>
        <th width="20%"><?php echo $this->translate('商品数量'); ?></th>
        <th width="11%"><?php echo $this->translate('操作'); ?></th>
    </tr>
    </thead>
    <?php if($this->goods_set_list) { foreach ($this->goods_set_list as $item_value) { ?>
        <tr>
            <td><?php echo $item_value['item_id']; ?></td>
            <td><?php echo $this->escapeHtml($item_value['item_title']); ?></td>
            <td><?php echo $this->escapeHtml($item_value['item_code']); ?></td>
            <td><?php echo $item_value['goods_num']; ?></td>
            <td>
                <a href="<?php echo $this->url('admintheme/default',array('action'=>'goodsSet'), array('query'=>array('theme_id'=>$item_value['theme_id'], 'item_id'=>$item_value['item_id']))); ?>"><?php echo $this->translate('编辑'); ?></a>
            </td>
        </tr>
    <?php } } ?>
</table>