<thead style="background: #CCC;">
<tr>
    <th width="7%"><?php echo $this->translate('排序'); ?></th>
    <th width="7%">ID</th>
    <th width="30%"><?php echo $this->translate('商品名称'); ?></th>
    <th width="9%"><?php echo $this->translate('商品货号'); ?></th>
    <th width="10%"><?php echo $this->translate('商品价格'); ?></th>
    <th width="7%"><?php echo $this->translate('状态'); ?></th>
    <th width="13%"><?php echo $this->translate('操作'); ?></th>
</tr>
</thead>
<?php
if ($this->goods_list) {
    foreach ($this->goods_list as $goods_value) {
        ?>
        <tr id="tag_goods_<?php echo $goods_value['goods_id']; ?>">
            <td><input type="text" name="theme_goods_id[<?php echo $goods_value['theme_goods_id']; ?>]" id="theme_goods_id_<?php echo $goods_value['theme_goods_id']; ?>" class="span12" value="<?php echo $goods_value['goods_sort']; ?>" /></td>
            <td><?php echo $goods_value['goods_id']; ?></td>
            <td><?php echo $this->escapeHtml($goods_value['goods_name']); ?></td>
            <td><?php echo $this->escapeHtml($goods_value['goods_item']); ?></td>
            <td><?php echo $goods_value['goods_shop_price']; ?></td>
            <td><?php echo (intval($goods_value['goods_state']) == 2 ? $this->translate('下架') : ($goods_value['goods_state']== 1 ? $this->translate('上架') : '')); ?></td>
            <td>
                <a href="javascript:;" onclick="return del_goods_js(<?php echo $goods_value['item_id'] ?>, <?php echo $goods_value['theme_goods_id']; ?>);"><?php echo $this->translate('删除'); ?></a>
            </td>
        </tr>
        <?php
    }
}
?>

