<div class="tabbable tabs-left">
              <ul class="nav nav-tabs">
              	<li><h5><?php echo $this->translate('导出设置'); ?></h5></li>
                <li class="active"><a data-toggle="tab" href="#export_a"><?php echo $this->translate('基本设置'); ?></a></li>
              </ul>
              <form class="form-horizontal" method="post" name="export_ship_form" id="export_ship_form">
              <div class="tab-content">
    			<div id="sticky_navigation" style="height:30px;border-bottom:4px solid #DFDFDF;">
        			<div class="pull-left" style="font-size:16px;line-height:30px;"><strong><?php echo $this->translate('导出发货单'); ?></strong></div>
        			<div id="sticky_navigation_right" class="pull-right">
                	<a href="<?php echo $this->url('orders/default', array('action'=>'shiplist', 'controller'=>'Orders')); ?>" class="btn btn-small"><i class="icon-arrow-left"></i> <?php echo $this->translate('返回发货单列表'); ?></a>&nbsp;
                	<a href="<?php echo $this->serverUrl(true); ?>" class="btn btn-small btn-warning"><i class="icon-repeat icon-white"></i> <?php echo $this->translate('刷新'); ?></a>&nbsp;
                	<button type="submit" onclick="$('#class_save_type').val('');" class="btn btn-small btn-primary"><i class="icon-ok icon-white"></i> <?php echo $this->translate('导出Excel文件'); ?></button>&nbsp;
                	<a href="<?php echo $this->myviewalias()->dbshopHelpUrl('export_ship_set'); ?>" target="_blank" class="btn btn-small btn-info"><i class="icon-info-sign icon-white"></i> <?php echo $this->translate('查看帮助说明'); ?></a>
                	</div>
        		</div>
                <div id="export_a" class="tab-pane active">
                	<div class="well admin_add_header_well"><?php echo $this->translate('基本设置'); ?></div>
                	<div class="well admin_add_well">
                        <div class="message_one">
                    	</div>
                    	<div class="control-group">
                  			<label for="input01" class="control-label"><?php echo $this->translate('必选导出'); ?>：</label>
           					<div class="controls">
                                <label class="checkbox inline"><input type="checkbox" disabled checked="checked"><?php echo $this->translate('收货人'); ?></label>
                                <label class="checkbox inline"><input type="checkbox" disabled checked="checked"><?php echo $this->translate('收货地址'); ?></label>
                                <label class="checkbox inline"><input type="checkbox" disabled checked="checked"><?php echo $this->translate('联系方式'); ?></label>
                                <label class="checkbox inline"><input type="checkbox" disabled checked="checked"><?php echo $this->translate('邮政编码'); ?></label>
                                <label class="checkbox inline"><input type="checkbox" disabled checked="checked"><?php echo $this->translate('送货时间'); ?></label>
                                <label class="checkbox inline"><input type="checkbox" disabled checked="checked"><?php echo $this->translate('付款方式'); ?></label>
                                <label class="checkbox inline"><input type="checkbox" disabled checked="checked"><?php echo $this->translate('应收货款'); ?></label>
            				</div>
                        </div>
                        <div class="control-group">
                            <label for="input01" class="control-label"><?php echo $this->translate('可选导出'); ?>：</label>
                            <div class="controls">
                                <label class="checkbox inline"><input type="checkbox" name="select_export_value[]" value="express_name"><?php echo $this->translate('快递信息'); ?></label>
                                <label class="checkbox inline"><input type="checkbox" name="select_export_value[]" value="express_fee"><?php echo $this->translate('配送费用'); ?></label>
                                <label class="checkbox inline"><input type="checkbox" name="select_export_value[]" value="express_number"><?php echo $this->translate('快递单号'); ?></label>
                                <label class="checkbox inline"><input type="checkbox" name="select_export_value[]" value="goods_name"><?php echo $this->translate('商品信息之商品名称'); ?></label>
                                <label class="checkbox inline"><input type="checkbox" name="select_export_value[]" value="goods_item"><?php echo $this->translate('商品信息之商品货号'); ?></label>
                                <label class="checkbox inline"><input type="checkbox" name="select_export_value[]" value="goods_extend_info"><?php echo $this->translate('商品信息之商品规格'); ?></label>
                                <label class="checkbox inline"><input type="checkbox" name="select_export_value[]" value="buy_num"><?php echo $this->translate('商品信息之购买数量'); ?></label>
                            </div>
                        </div>
                    	<div class="control-group">
                  			<label for="input01" class="control-label"><?php echo $this->translate('开始时间'); ?>：</label>
           					<div class="controls">
              					<input type="text" id="export_start_time" name="export_start_time" class="span2 Wdate" onclick="WdatePicker({el:'export_start_time'})">
                                <i class="cus-help shop_admin_help_note" data-content="<?php echo $this->translate('订单下单时间'); ?>"></i>
            				</div>                        
                        </div>
                        <div class="control-group">
                            <label for="input01" class="control-label"><?php echo $this->translate('结束时间'); ?>：</label>
                            <div class="controls">
                                <input type="text" id="export_end_time" name="export_end_time" class="span2 Wdate" onclick="WdatePicker({el:'export_end_time'})">
                                <i class="cus-help shop_admin_help_note" data-content="<?php echo $this->translate('订单下单时间'); ?>"></i>
                            </div>
                        </div>
                        <div class="control-group">
                            <label for="input01" class="control-label"><?php echo $this->translate('配送方式'); ?>：</label>
                            <div class="controls">
                                <select id="express_id" name="express_id" class="span2">
                                    <option value=""><?php echo $this->translate('全部方式'); ?></option>
                                    <?php if($this->express_array) foreach ($this->express_array as $express_value) { ?>
                                    <option value="<?php echo $express_value['express_id']; ?>"><?php echo $this->escapeHtml($express_value['express_name']); ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                        </div>
                        <div class="control-group">
                            <label for="input01" class="control-label"><?php echo $this->translate('发货状态'); ?>：</label>
                            <div class="controls">
                                <select id="order_ship_state" name="order_ship_state" class="span2">
                                    <option value="all_ship"><?php echo $this->translate('全部状态'); ?></option>
                                    <option value="no_ship"><?php echo $this->translate('未发货'); ?></option>
                                    <option value="yes_ship"><?php echo $this->translate('已发货'); ?></option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>

             </div>
              </form>
</div>
<script src="<?php echo $this->basePath('/public/js/DatePicker/WdatePicker.js'); ?>"></script>
