<div class="tabbable tabs-left">
              <ul class="nav nav-tabs">
              	<li><h5><?php echo $this->translate('订单操作'); ?></h5></li>
                <li class="active"><a data-toggle="tab" href=""><?php echo $this->translate('收货操作'); ?></a></li>
              </ul>
              <form class="form-horizontal" name="order_oper_form" id="order_oper_form" method="post" action="">
              <input type="hidden" name="order_id" id="order_id" value="<?php echo $this->order_info->order_id; ?>" />
              <div class="tab-content">
    			<div style="height:30px;border-bottom:4px solid #DFDFDF;">
        			<div class="pull-left" style="font-size:16px;line-height:30px;"><strong><?php echo $this->translate('订单'); ?>&nbsp;<?php echo $this->order_info->order_sn; ?>&nbsp;|&nbsp;<?php echo date("Y-m-d H:i", $this->order_info->order_time); ?></strong></div>
        			<div class="pull-right">
                	<a href="<?php echo $this->url('orders/default/order_id',array('action'=>'edit','controller'=>'Orders','order_id'=>$this->order_info->order_id,'page'=>$this->page)); ?>" class="btn btn-small"><i class="icon-arrow-left"></i> <?php echo $this->translate('返回订单'); ?></a>&nbsp;
                	<button type="submit" class="btn btn-small btn-primary"><i class="icon-ok icon-white"></i> <?php echo $this->translate('点击完成订单'); ?></button>&nbsp;
                	<a href="<?php echo $this->myviewalias()->dbshopHelpUrl('order_finish_set'); ?>" target="_blank" class="btn btn-small btn-info"><i class="icon-info-sign icon-white"></i> <?php echo $this->translate('查看帮助说明'); ?></a>
                	</div>
        		</div>
                <div id="user_a" class="tab-pane active">
                	<div class="well admin_add_header_well"><?php echo $this->translate('收货操作'); ?></div>
                	<div class="well admin_add_well">
                    	<div class="control-group">
                  			<label for="input01" class="control-label"><?php echo $this->translate('订单状态'); ?>：</label>
           					<div class="controls">
                            	<label><?php echo $this->translate('确认收货'); ?><input type="hidden" id="order_state" name="order_state" value="60" /></label>
            				</div>                        
                        </div>
                    	<div class="control-group">
                  			<label for="input01" class="control-label"><?php echo $this->translate('操作说明'); ?>：</label>
           					<div class="controls">
              					<textarea class="span8" name="state_info" id="state_info" rows="3"></textarea>
            				</div>                        
                        </div>
                                                                                                                       
                  	</div>
                </div>
             </div>
              </form>
</div>