<div class="tabbable tabs-left">
              <ul class="nav nav-tabs">
              	<li><h5><?php echo $this->translate('批量导入'); ?></h5></li>
                <li class="active"><a data-toggle="tab" href="#export_a"><?php echo $this->translate('基本设置'); ?></a></li>
              </ul>
              <form class="form-horizontal" method="post" name="import_ship_form" id="import_ship_form" enctype="multipart/form-data">
              <div class="tab-content">
    			<div id="sticky_navigation" style="height:30px;border-bottom:4px solid #DFDFDF;">
        			<div class="pull-left" style="font-size:16px;line-height:30px;"><strong><?php echo $this->translate('批量导入快递单号'); ?></strong></div>
        			<div id="sticky_navigation_right" class="pull-right">
                	<a href="<?php echo $this->url('orders/default', array('action' => 'expressNumber', 'controller' => 'Orders')); ?>" class="btn btn-small"><i class="icon-arrow-left"></i> <?php echo $this->translate('返回快递单号管理'); ?></a>&nbsp;
                	<a href="<?php echo $this->serverUrl(true); ?>" class="btn btn-small btn-warning"><i class="icon-repeat icon-white"></i> <?php echo $this->translate('刷新'); ?></a>&nbsp;
                	<button type="submit" class="btn btn-small btn-primary"><i class="icon-ok icon-white"></i> <?php echo $this->translate('导入Excel文件'); ?></button>&nbsp;
                	<a href="<?php echo $this->myviewalias()->dbshopHelpUrl('order_express_number'); ?>" target="_blank" class="btn btn-small btn-info"><i class="icon-info-sign icon-white"></i> <?php echo $this->translate('查看帮助说明'); ?></a>
                	</div>
        		</div>
                <div id="export_a" class="tab-pane active">
                	<div class="well admin_add_header_well"><?php echo $this->translate('基本设置'); ?></div>
                	<div class="well admin_add_well">
                        <div class="message_one">
                    	</div>
                        <div class="control-group">
                            <label for="input01" class="control-label"><?php echo $this->translate('导入文件'); ?>：</label>
                            <div class="controls">
                                <input type="file" name="import_excel_file" id="import_excel_file">
                            </div>
                        </div>
                        <div class="control-group">
                            <label for="input01" class="control-label"><?php echo $this->translate('配送方式'); ?>：</label>
                            <div class="controls">
                                <select id="express_id" name="express_id" class="span2">
                                    <?php if($this->express_array) foreach ($this->express_array as $express_value) { ?>
                                    <option <?php if($express_value['express_id'] == $this->express_id) echo 'selected'; ?> value="<?php echo $express_value['express_id']; ?>"><?php echo $this->escapeHtml($express_value['express_name']); ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                        </div>
                        <div class="control-group">
                            <label for="input01" class="control-label"><?php echo $this->translate('例子文件'); ?>：</label>
                            <div class="controls">
                                <a href="<?php echo $this->url('orders/default', array('action' => 'exampleExcel', 'controller' => 'Orders')); ?>" class="btn btn-small btn-primary"><i class="icon-download-alt icon-white"></i> <?php echo $this->translate('下载Excel例子文件'); ?></a>
                            </div>
                        </div>
                    </div>
                </div>

             </div>
              </form>
</div>
