    		<div style="height:30px;border-bottom:4px solid #DFDFDF;">
        	<p class="pull-left" style="font-size:16px; line-height:30px;"><strong><?php echo $this->translate('支付记录'); ?></strong> <i class="cus-help shop_admin_help_note" data-content="<?php echo $this->translate('此处显示的是已付款或者货到付款订单的支付记录'); ?>"></i></p>
			<p class="pull-right">
			<a href="<?php echo $this->myviewalias()->dbshopHelpUrl('order_pay_log'); ?>" target="_blank" class="btn btn-small btn-info"><i class="icon-info-sign icon-white"></i> <?php echo $this->translate('查看帮助说明'); ?></a>
			</p>
        	</div>
            <table class="table table-hover">
            <thead style="background:#CCC;">
            	<tr>
                    <th width="10%"><?php echo $this->translate('订单号'); ?></th>
                    <th width="10%"><?php echo $this->translate('支付方式'); ?></th>
                    <th width="10%"><?php echo $this->translate('下单时间'); ?></th>
                    <th width="10%"><?php echo $this->translate('购买人'); ?></th>
                    <th width="10%"><?php echo $this->translate('支付时间'); ?></th>
                    <th width="10%"><?php echo $this->translate('支付状态'); ?></th>
                </tr>
            </thead>
            <?php
			if ($this->pay_list) {
				foreach ($this->pay_list as $pay_val) {
			?>            
            <tr>
            	<td><a href="<?php echo $this->url('orders/default/order_id',array('action'=>'edit','controller'=>'Orders','order_id'=>$pay_val['order_id'])); ?>"><?php echo $pay_val['order_sn']; ?></a></td>
            	<td><?php echo $this->escapeHtml($pay_val['pay_name']); ?></td>
                <td><?php echo date('Y-m-d H:i:s',$pay_val['order_time']); ?></td>
                <td><?php echo $this->escapeHtml($pay_val['buyer_name']); ?></td>
                <td><?php echo ($pay_val['order_state']>=20 and $pay_val['pay_code']!='hdfk') ? date('Y-m-d H:i:s',$pay_val['pay_time']) : $this->translate('无'); ?></td>
                <td><?php 
				if($pay_val['order_state']>=20 and $pay_val['pay_code']!='hdfk') echo $this->translate('已支付');
				elseif($pay_val['order_state']<60 and $pay_val['pay_code']=='hdfk') echo $this->translate('未支付');
				elseif($pay_val['order_state']==60 and $pay_val['pay_code']=='hdfk') echo $this->translate('已支付');
				?></td> 
            </tr>
            <?php
				}
			}
			?>
            <tr>
			<td colspan="9" style="background: #FFF">
				<?php echo ( count($this->pay_list) > 0 ) ? $this->paginationControl($this->pay_list, 'Sliding', 'common/pager',array('page_url'=>$this->url('orders/default/page',array('controller'=>'Orders', 'action'=>'paylog')))) : ""; ?>
                </td>
		</tr>
            </table>