<div class="tabbable tabs-left">
              <ul class="nav nav-tabs">
              	<li><h5><?php echo $this->translate('订单操作'); ?></h5></li>
                <li class="active"><a data-toggle="tab" href=""><?php echo $this->translate('发货操作'); ?></a></li>
              </ul>
              <form class="form-horizontal" name="order_oper_form" id="order_oper_form" method="post" action="">
              <input type="hidden" name="order_id" id="order_id" value="<?php echo $this->order_info->order_id; ?>" />
              <div class="tab-content">
    			<div style="height:30px;border-bottom:4px solid #DFDFDF;">
        			<div class="pull-left" style="font-size:16px;line-height:30px;"><strong><?php echo $this->translate('订单'); ?>&nbsp;<?php echo $this->order_info->order_sn; ?>&nbsp;|&nbsp;<?php echo date("Y-m-d H:i", $this->order_info->order_time); ?></strong></div>
        			<div class="pull-right">
                    <?php if($this->url_type == 'show_ship') { ?>
                    <a href="<?php echo $this->url('orders/default/order_id',array('action'=>'showShip','controller'=>'Orders','order_id'=>$this->order_info->order_id,'page'=>$this->page)); ?>" class="btn btn-small"><i class="icon-arrow-left"></i> <?php echo $this->translate('返回发货单'); ?></a>&nbsp;
                    <?php } else { ?>
                	<a href="<?php echo $this->url('orders/default/order_id',array('action'=>'edit','controller'=>'Orders','order_id'=>$this->order_info->order_id,'page'=>$this->page)); ?>" class="btn btn-small"><i class="icon-arrow-left"></i> <?php echo $this->translate('返回订单'); ?></a>&nbsp;
                    <?php } ?>
					<?php if(!isset($this->v_stock_few) or (isset($this->v_stock_few) and empty($this->v_stock_few))) { ?>
                	<button type="submit" class="btn btn-small btn-primary"><i class="icon-ok icon-white"></i> <?php echo $this->translate('点击发货'); ?></button>&nbsp;
                	<?php } ?>
					<a href="<?php echo $this->myviewalias()->dbshopHelpUrl('order_ship_set'); ?>" target="_blank" class="btn btn-small btn-info"><i class="icon-info-sign icon-white"></i> <?php echo $this->translate('查看帮助说明'); ?></a>
                	</div>
        		</div>
                <div id="user_a" class="tab-pane active">
                	<div class="well admin_add_header_well"><?php echo $this->translate('发货操作'); ?></div>
                	<div class="well admin_add_well">
						<?php if(isset($this->v_stock_few) and !empty($this->v_stock_few)) { ?>
						<div class="alert alert-error">
							<h4><?php echo $this->translate('虚拟商品'); ?></h4>
							<?php foreach($this->v_stock_few as $vGoods) { ?>
								<p><?php echo '<strong>'.$this->translate('商品名称').'：</strong>'.$this->escapeHtml($vGoods['goods_name']).'&nbsp;&nbsp;<strong>'.$this->translate('需补货数量：').$vGoods['num'].'</strong>';?></p>
							<?php } ?>
						</div>
						<?php } ?>
						<?php if(isset($this->delivery_address) and $this->virtual_all_goods == 'no') { ?>
                    	<div class="control-group">
                  			<label for="input01" class="control-label"><?php echo $this->translate('快递信息'); ?>：</label>
           					<div class="controls">
              					<label><?php echo $this->delivery_address->express_name; ?></label>
            				</div>                        
                        </div>
                    	<div class="control-group">
                  			<label for="input01" class="control-label"><?php echo $this->translate('配送费用'); ?>：</label>
           					<div class="controls">
              					<label>¥<?php echo $this->delivery_address->express_fee; ?></label>
            				</div>                        
                        </div>
                    	<div class="control-group">
                  			<label for="input01" class="control-label"><?php echo $this->translate('送货时间'); ?>：</label>
           					<div class="controls">
              					<label><?php echo $this->delivery_address->express_time_info; ?></label>
            				</div>                        
                        </div>
						<?php } ?>
                    	<div class="control-group">
                  			<label for="input01" class="control-label"><?php echo $this->translate('发货状态'); ?>：</label>
           					<div class="controls">
                            	<label style="line-height: 30px;"><?php echo $this->translate('发货'); ?><input type="hidden" id="ship_state" name="ship_state" value="40" /></label>
            				</div>                        
                        </div>
						<?php if(isset($this->express_number) and $this->virtual_all_goods == 'no') { ?>
                    	<div class="control-group">
                  			<label for="input01" class="control-label"><?php echo $this->translate('快递单号'); ?>：</label>
           					<div class="controls">
              					<input type="text" class="span4" id="express_number" name="express_number" value="<?php if(isset($this->express_number->express_number) and !empty($this->express_number->express_number)) echo $this->express_number->express_number; ?>" />
            				</div>                        
                        </div>
						<?php } ?>
                    	<div class="control-group">
                  			<label for="input01" class="control-label"><?php echo $this->translate('操作说明'); ?>：</label>
           					<div class="controls">
              					<textarea class="span8" name="state_info" id="state_info" rows="3"></textarea>
            				</div>                        
                        </div>
                                                                                                                       
                  	</div>
                </div>
             </div>
              </form>
</div>