<ul class="clearfix">
    <?php
    if(isset($_COOKIE['view_goods'])) {
        $viewGoodsArray = unserialize($_COOKIE['view_goods']);
        if(is_array($viewGoodsArray) and !empty($viewGoodsArray)) {
            foreach($viewGoodsArray as $vGoodsValue) {
                ?>
                <li>
                    <a target="_blank" title="<?php echo $this->escapeHtml($vGoodsValue['goods_name']); ?>" href="<?php echo $this->url('frontgoods/default', array('goods_id'=>$vGoodsValue['goods_id'], 'class_id'=>$vGoodsValue['class_id'])); ?>">
                        <img alt="<?php echo $this->escapeHtml($vGoodsValue['goods_name']); ?>" src="<?php echo $this->basePath($this->frontwebsite()->shopGoodsImage($vGoodsValue['image'])); ?>">
                    </a>
                </li>
            <?php } } } ?>
</ul>