<?php if ($this->goods_list->getTotalItemCount() > 0) { foreach ($this->goods_list as $goods_value) { ?>
    <li class="single_item">
        <a href="<?php echo $this->url('m_goods/default', array('goods_id'=>$goods_value['goods_id'], 'class_id'=>$goods_value['one_class_id'])); ?>"><img alt="<?php echo $this->escapeHtml($goods_value['goods_name']); ?>" src="<?php echo $this->basePath($this->frontwebsite()->shopGoodsImage($goods_value['goods_thumbnail_image'])); ?>"></a>
        <dl>
            <dt>
            <h4 class="title"><a href="<?php echo $this->url('m_goods/default', array('goods_id'=>$goods_value['goods_id'], 'class_id'=>$goods_value['one_class_id'])); ?>"><?php echo $this->escapeHtml($goods_value['goods_name']); ?></a></h4>
            </dt>
            <dd>
                    <span class="pull-left"><strong><?php echo $this->translate('价格'); ?>：<b class="ect-colory"><?php
                                $goodsPrice = (isset($goods_value['group_price']) and $goods_value['group_price'] > 0) ? $goods_value['group_price'] : $goods_value['goods_shop_price'];
                                echo $this->frontwebsite()->shopPriceExtend($goodsPrice);
                                ?></b></strong>
                        <?php if(isset($goods_value['goods_price'])) { ?><small class="ect-margin-lr"><del><?php echo $this->frontwebsite()->shopPriceExtend($goods_value['goods_price']); ?></del></small><?php } ?>
                    </span>
            </dd>
            <dd><span class="pull-left "><i class="fa fa-heart-o"></i> <?php echo $goods_value['love_num']; ?><?php echo $this->translate('人喜欢'); ?></span><span class="pull-right"><?php echo $this->translate('销量'); ?>：<?php echo intval($goods_value['buy_num']+$goods_value['virtual_sales']); ?><?php echo $this->translate('件'); ?></span> </dd>
        </dl>
    </li>
<?php } ?>
<li class="more_goods_page"><?php echo ( count($this->goods_list) > 0 ) ? $this->paginationControl($this->goods_list, 'Sliding', 'mobile/moreajax',array('page_url'=>$this->url('m_class/default',array('action'=>'goodsSearch', 'controller'=>'Class', 'class_id'=>0)), 'ajaxFunction'=>'goods_ajax_list')) : ""; ?></li>
<?php } else { echo '<li>' . $this->translate('暂无商品！') . '</li>'; } ?>