<div class="site-footer">
    <?php
    $index_footer_chengnuo = $this->frontwebsite()->getTagArticleArray('index_chengnuo');
    if ($index_footer_chengnuo) {
        ?>
        <div class="footer-service">
        <div class="container">
            <ul class="list-service clearfix">
                <?php
                $chengnuo_ico_array = array(
                    0 => '<i class="iconfont"></i>',
                    1 => '<i class="iconfont"></i>',
                    2 => '<i class="iconfont"></i>',
                    3 => '<i class="iconfont"></i>',
                    4 => '<i class="iconfont"></i>',
                );
                foreach($index_footer_chengnuo as $footer_chengnuo_key => $footer_chengnuo_val) {
                    ?>
                    <li class="li_service">
                        <a target="_blank" href="<?php echo $this->url('frontarticle/default/cms_id',array('action'=>'single','cms_id'=>$footer_chengnuo_val['single_article_id'])); ?>">
                            <?php echo $chengnuo_ico_array[$footer_chengnuo_key]; ?>
                            <strong><?php echo $this->escapeHtml($footer_chengnuo_val['single_article_title']); ?></strong>
                        </a>
                    </li>
                <?php } ?>
            </ul>
        </div>
        </div>
    <?php } ?>
    <div class="container">
        <div class="footer-links clearfix">
            <dl class="col-links col-links-first">
                <dt><?php echo $this->translate('帮助中心'); ?></dt>
                <?php
                $index_footer_help = $this->frontwebsite()->getTagArticleArray('index_help');
                if ($index_footer_help) {
                    foreach($index_footer_help as $footer_felp_val) {
                ?>
                <dd>
                    <a target="_blank" href="<?php echo $this->url('frontarticle/default/cms_id',array('action'=>'single','cms_id'=>$footer_felp_val['single_article_id'])); ?>">
                        <?php echo $this->escapeHtml($footer_felp_val['single_article_title']); ?>
                    </a>
                </dd>
                <?php } } ?>
            </dl>
            <dl class="col-links">
                <dt><?php echo $this->translate('服务支持'); ?></dt>
                <?php
                $index_footer_service = $this->frontwebsite()->getTagArticleArray('index_service');
                if ($index_footer_service) {
                    foreach($index_footer_service as $footer_service_val) {
                        ?>
                        <dd>
                            <a target="_blank" href="<?php echo $this->url('frontarticle/default/cms_id',array('action'=>'single','cms_id'=>$footer_service_val['single_article_id'])); ?>">
                                <?php echo $this->escapeHtml($footer_service_val['single_article_title']); ?>
                            </a>
                        </dd>
                    <?php } } ?>
            </dl>
            <dl class="col-links">
                <dt><?php echo $this->translate('支付方式'); ?></dt>
                <?php
                $index_footer_pay = $this->frontwebsite()->getTagArticleArray('index_pay');
                if ($index_footer_pay) {
                    foreach($index_footer_pay as $footer_pay_val) {
                        ?>
                        <dd>
                            <a target="_blank" href="<?php echo $this->url('frontarticle/default/cms_id',array('action'=>'single','cms_id'=>$footer_pay_val['single_article_id'])); ?>">
                                <?php echo $this->escapeHtml($footer_pay_val['single_article_title']); ?>
                            </a>
                        </dd>
                    <?php } } ?>
            </dl>
            <dl class="col-links">
                <dt><?php echo $this->translate('关于我们'); ?></dt>
                <?php
                $index_footer_about = $this->frontwebsite()->getTagArticleArray('index_about');
                if ($index_footer_about) {
                    foreach($index_footer_about as $footer_about_val) {
                        ?>
                        <dd>
                            <a target="_blank" href="<?php echo $this->url('frontarticle/default/cms_id',array('action'=>'single','cms_id'=>$footer_about_val['single_article_id'])); ?>">
                                <?php echo $this->escapeHtml($footer_about_val['single_article_title']); ?>
                            </a>
                        </dd>
                    <?php } } ?>
            </dl>
            <dl class="col-links">
                <dt><?php echo $this->translate('客服中心'); ?></dt>
                <?php
                $index_footer_customer_service = $this->frontwebsite()->getTagArticleArray('index_customer');
                if ($index_footer_customer_service) {
                    foreach($index_footer_customer_service as $footer_customer_service_val) {
                        ?>
                        <dd>
                            <a target="_blank" href="<?php echo $this->url('frontarticle/default/cms_id',array('action'=>'single','cms_id'=>$footer_customer_service_val['single_article_id'])); ?>">
                                <?php echo $this->escapeHtml($footer_customer_service_val['single_article_title']); ?>
                            </a>
                        </dd>
                    <?php } } ?>
            </dl>
            <div class="col-contact">
                <?php
                $index_footer_tel = $this->frontwebsite()->getTagArticleArray('index_tel');
                if ($index_footer_tel) {
                    echo $index_footer_tel[0]['single_article_body'];
                }
                ?>
            </div>
        </div>
        <div class="footer-info clearfix">
            <?php  if ($this->index_flink_list) { ?>
            <div class="info-links" style="margin-bottom: 8px;">
                <?php
                foreach ($this->index_flink_list as $flink_value) {
                ?>
                <a href="<?php echo $flink_value['links_url']; ?>" target="_blank" title="<?php echo $flink_value['links_webname']; ?>"><img src="<?php echo $this->basePath($flink_value['links_logo']); ?>" style="border: 1px solid #dfdfdf;"></a>
                <?php } ?>
            </div>
            <?php } ?>
            <div style="position:relative;" class="info-text">
