<div class="tabbable tabs-left">
    <?php echo $this->partial('analytics/analytics/left_menu.phtml'); ?>
    <div class="tab-content">
        <table class="table table-hover table-striped table-bordered">
            <thead>
            <th><?php echo $this->translate('销售排行'); ?></th>
            </thead>
            <tbody>
            <tr style="font-weight: bold;">
                <form method="get" name="sale_order_form" id="sale_order_form" action="">
                    <input type="hidden" name="dateNum" value="<?php if($this->date_num > 0) echo $this->date_num+1; ?>">
                    <td colspan="6" style="text-align: right;line-height: 40px;background: #f9f9f9">
                        <a href="<?php echo $this->url('analytics/default', array('controller'=>'Analytics', 'action'=>'saleOrder'), array('query'=>array('dateNum'=>7))) . ((isset($this->group_id) and $this->group_id > 0) ? '&group_id='.$this->group_id : ''); ?>" class="btn <?php if($this->date_num == 6) echo 'btn-primary'; ?>"><?php echo $this->translate('最近7天'); ?></a>&nbsp;
                        <a href="<?php echo $this->url('analytics/default', array('controller'=>'Analytics', 'action'=>'saleOrder'), array('query'=>array('dateNum'=>30))) . ((isset($this->group_id) and $this->group_id > 0) ? '&group_id='.$this->group_id : ''); ?>" class="btn <?php if($this->date_num == 29) echo 'btn-primary'; ?>"><?php echo $this->translate('最近30天'); ?></a>&nbsp;&nbsp;
                        <select name="group_id" onchange="submit_form()" class="span2" style="width: 150px;">
                            <option value=""><?php echo $this->translate('选择客户组'); ?></option>
                            <?php if(!empty($this->group_array)) { foreach($this->group_array as $group_value) { ?>
                                <option value="<?php echo $group_value['group_id']; ?>" <?php if(isset($this->group_id) and $this->group_id == $group_value['group_id']) echo 'selected'; ?>><?php echo $this->escapeHtml($group_value['group_name']); ?></option>
                            <?php } } ?>
                        </select>
                        <input type="text" class="span2 Wdate" name="start_time" id="start_time" value="<?php if(isset($this->start_time)) echo $this->start_time; ?>" onclick="WdatePicker({el:'start_time', dateFmt:'yyyy-MM-dd'})">
                        ~
                        <input type="text" class="span2 Wdate" name="end_time" id="end_time" value="<?php if(isset($this->end_time)) echo $this->end_time; ?>"  onclick="WdatePicker({el:'end_time', dateFmt:'yyyy-MM-dd'})">
                        <button type="submit" class="btn btn-primary"><?php echo $this->translate('查看'); ?></button>
                    </td>
                </form>
            </tr>
            <tr>
                <td width="10%" style="background:#CCC;"><b><?php echo $this->translate('排行'); ?></b></td>
                <td width="30%" style="background:#CCC;"><b><?php echo $this->translate('商品名称'); ?></b></td>
                <td width="15%" style="background:#CCC;"><b><?php echo $this->translate('商品货号'); ?></b></td>
                <td width="15%" style="background:#CCC;"><b><?php echo $this->translate('商品销量'); ?></b></td>
                <td width="15%" style="background:#CCC;"><b><?php echo $this->translate('商品销售额'); ?></b></td>
                <td width="15%" style="background:#CCC;"><b><?php echo $this->translate('商品均价'); ?></b></td>
            </tr>
            <?php
            if($this->order_goods_list) {
                foreach ($this->order_goods_list as $g_key => $g_value) {
                    ?>
                    <tr>
                        <td><?php echo $this->page_base_num + $g_key+1; ?></td>
                        <td><?php echo $this->escapeHtml($g_value['goods_name']); ?></td>
                        <td><?php echo $g_value['goods_item']; ?></td>
                        <td><?php echo $g_value['buy_g_num']; ?></td>
                        <td><?php echo number_format($g_value['goods_g_amount'], 2, '.', ''); ?></td>
                        <td><?php echo number_format($g_value['goods_g_amount']/$g_value['buy_g_num'], 2, '.', ''); ?></td>
                    </tr>
                <?php } } ?>
            <tr>
                <td colspan="6" style="background:#FFF">
                    <?php echo ( count($this->order_goods_list) > 0 ) ? $this->paginationControl($this->order_goods_list,'Sliding','common/pager',array('page_url'=>$this->url('analytics/default/page',array('controller'=>'Analytics', 'action'=>'saleOrder')))) : ''; ?>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>
<script src="<?php echo $this->basePath('/public/js/DatePicker/WdatePicker.js'); ?>"></script>
<script>
    function submit_form() {
        $('#sale_order_form').submit();
    }
</script>
