<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel"><?php echo $this->translate('选择商品'); ?></h3>
</div>
<div class="modal-body" style="padding: 0 10px 0 10px;">
    <div class="control-group">
        <div class="controls">
            <select name="class_id" id="class_id" class="span5">
                <option value=""><?php echo $this->translate('选择商品分类'); ?></option>
                <?php
                if (isset($this->goods_class) and !empty($this->goods_class)) {
                    foreach ($this->goods_class as $class_val) {
                        ?>
                        <option value="<?php echo $class_val['class_id'] ?>" <?php if( isset($this->class_id) and $this->class_id == $class_val['class_id']) { ?>selected="selected"<?php } ?>><?php echo str_repeat('&nbsp;', $class_val['class_level'] * 5).$class_val['class_name']; ?></option>
                    <?php } } ?>
            </select>
            <button type="button" class="btn btn-primary" onclick="searchGoods();"><?php echo $this->translate('搜索'); ?></button>
        </div>
    </div>

    <table class="table table-hover">
        <thead style="background:#CCC;">
        <tr>
            <th width="5%">
                    <input type="checkbox"  id="select_checkbox_state" onclick="selectCheckBox('check_goods_id', 'select_checkbox_state');">
            </th>
            <th width="5%">ID</th>
            <th width="52%"><?php echo $this->translate('商品名称'); ?></th>
            <th width="20%"><?php echo $this->translate('商品价格'); ?></th>
            <th><?php echo $this->translate('状态'); ?></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($this->goods_list as $goods_value) { ?>
        <tr>
            <td><input type="checkbox" name="check_goods_id[]" value="<?php echo $goods_value['goods_id']; ?>"></td>
            <td><?php echo $goods_value['goods_id']; ?></td>
            <td><?php echo $this->escapeHtml($goods_value['goods_name']); ?></td>
            <td><?php echo $goods_value['goods_shop_price']; ?></td>
            <td><?php echo (intval($goods_value['goods_state']) == 2 ? $this->translate('下架') : ($goods_value['goods_state']== 1 ? $this->translate('上架') : '')); ?></td>
        </tr>
        <?php } ?>
        </tbody>
    </table>
    <div class="text-right">
        <?php echo ( $this->goods_list->getTotalItemCount() > 0 ) ? $this->paginationControl($this->goods_list, 'Sliding', 'common/ajax-pages',array('page_url'=>$this->url('goods/default/page',array('action'=>'ajaxGoodsList', 'id'=>0)), 'show_div_id'=>$this->show_div_id)) : ""; ?>
    </div>
</div>
<div class="modal-footer">
    <button type="button" onclick="add_more_goods();" class="btn btn-primary"><?php echo $this->translate('添加商品'); ?></button>
    <button class="btn" data-dismiss="modal" aria-hidden="true"><?php echo $this->translate('关闭'); ?></button>
</div>