    		<div id="sticky_navigation" style="height:30px;border-bottom:4px solid #DFDFDF;">
        	<p class="pull-left" style="font-size:16px; line-height:30px;"><strong><?php echo $this->translate('删除无用的商品图片'); ?> | </strong><?php echo $this->translate('这些图片在任何商品中都无法看到，不属于任何商品'); ?></p>
        	<p class="pull-right">
                <a href="<?php echo $this->url('goods/default',array('controller'=>'goods')); ?>" class="btn btn-small"><i class="icon-arrow-left"></i> <?php echo $this->translate('返回商品列表'); ?></a>&nbsp;
        	<a href="<?php echo $this->myviewalias()->dbshopHelpUrl('clear_goods_image'); ?>" target="_blank" class="btn btn-small btn-info"><i class="icon-info-sign icon-white"></i> <?php echo $this->translate('查看帮助说明'); ?></a>
        	</p>
        	</div>
            <table class="table table-hover">
            <thead style="background:#CCC;">
            	<tr>
                    <th width="10%"><?php echo $this->translate('图片ID'); ?></th>
                    <th width="20%"><?php echo $this->translate('图片名称'); ?></th>
                    <th width="50%"><?php echo $this->translate('图片'); ?></th>
                    <th width="15%"><?php echo $this->translate('操作'); ?></th>
                </tr>
            </thead>
            <?php if(is_array($this->clear_goods_image) and !empty($this->clear_goods_image)) foreach ($this->clear_goods_image as $image_value) { ?>
            <tr  id="image_<?php echo $image_value['goods_image_id']; ?>">
            	<td style="vertical-align:middle"><?php echo $image_value['goods_image_id']; ?></td>
            	<td style="vertical-align:middle"><?php echo basename($image_value['goods_title_image']); ?></td>
                <td><img src="<?php echo $this->basePath($this->frontwebsite()->shopadminGoodsImage($image_value['goods_thumbnail_image'])); ?>" style="width: 100px;" border="0"></td>
            	<td style="vertical-align:middle">
                    <a href="javascript:;" onclick="return del_image(<?php echo $image_value['goods_image_id']; ?>, '<?php echo basename($image_value['goods_title_image']); ?>');" class="btn btn-small btn-danger"><i class="icon-trash icon-white"></i> <?php echo $this->translate('删除'); ?></a>
            	</td>
            </tr>
            <?php
				}
			?>
            </table>
<script>
    function del_image(image_id, goods_image_name) {
        if(window.confirm('<?php echo $this->translate('您确实删除图片'); ?>'+goods_image_name+'？')) {
            $.post("<?php echo $this->url('goods/default',array('action'=>'clearGoodsImage','controller'=>'goods')); ?>",{goods_image_id:image_id},
                function(data){
                    if(data != 'false') {
                        $("#image_"+image_id).remove();
                        return true;
                    } else {
                        alert('<?php echo $this->translate('图片'); ?>'+goods_image_name+'<?php echo $this->translate('删除失败！'); ?>');
                    }
                });
        }
        return false;
    }
</script>