    		<div id="sticky_navigation" style="height:30px;border-bottom:4px solid #DFDFDF;">
        	<p class="pull-left" style="font-size:16px; line-height:30px;"><strong><?php echo $this->translate('配送管理'); ?></strong></p>
        	<p class="pull-right">
            <a href="<?php echo $this->url('express/default',array('action'=>'add')); ?>" class="btn btn-small btn-primary"><i class="icon-plus icon-white"></i> <?php echo $this->translate('添加配送方式'); ?></a>&nbsp;
            <a href="<?php echo $this->myviewalias()->dbshopHelpUrl('express_set'); ?>" target="_blank" class="btn btn-small btn-info"><i class="icon-info-sign icon-white"></i> <?php echo $this->translate('查看帮助说明'); ?></a>
            </p>
        	</div>
            <table class="table table-hover">
            <thead style="background:#CCC;">
            	<tr>
                    <th width="5%">ID</th>
                    <th width="15%"><?php echo $this->translate('配送名称'); ?></th>
                    <th width="42%"><?php echo $this->translate('配送简介'); ?></th>
                    <th width="10%"><?php echo $this->translate('配送排序'); ?></th>
                    <th width="10%"><?php echo $this->translate('货到付款'); ?></th>
                    <th width="8%"><?php echo $this->translate('状态'); ?></th>
                    <th width="10%"><?php echo $this->translate('操作'); ?></th>
                </tr>
            </thead>
            <?php if($this->express_array) foreach ($this->express_array as $express_value) { ?>            
            <tr>
            	<td><?php echo $express_value['express_id']; ?></td>
            	<td><?php echo $this->escapeHtml($express_value['express_name']); ?></td>
                <td><?php echo $this->escapeHtml($express_value['express_info']); ?></td>
                <td><?php echo $express_value['express_sort']; ?></td>
                <td><?php if($express_value['cash_on_delivery'] == 1) echo $this->translate('支持'); else echo $this->translate('不支持'); ?></td>
                <td><?php if($express_value['express_state'] == 1) echo $this->translate('开启'); else echo $this->translate('关闭'); ?></td>
            	<td><a href="<?php echo $this->url('express/default/express-id',array('action'=>'edit','controller'=>'express','express_id'=>$express_value['express_id'])); ?>"><?php echo $this->translate('编辑'); ?></a><span>|</span><a href="javascript:;" onclick="return express_del_js(<?php echo $express_value['express_id']; ?>);"><?php echo $this->translate('删除'); ?></a></td>  
            </tr>
            <?php
				}
			?>
            </table>
            
<script>
//配送方式删除js
function express_del_js(express_id) {
	if(window.confirm('<?php echo $this->translate('您确实要删除该配送方式吗？'); ?>')) {
	$.post("<?php echo $this->url('express/default',array('action'=>'del')); ?>",{express_id:express_id},
	function(data){
		if(data != 'false') {
			window.location.href='<?php echo $this->url('express/default'); ?>';
			return true;
		} else {
			alert('<?php echo $this->translate('配送方式删除失败！'); ?>');
		}
	});
	}
	return false;
}
</script>